/**
 * Prebuilt workflow rule templates for common MSP automation scenarios.
 * These are imported per-tenant via the API.
 */

export const PREBUILT_WORKFLOW_TEMPLATES = [
  {
    id: 'tpl-customer-reminder',
    name: 'Waiting on Customer Reminder',
    description: 'Send customer a follow-up email after 3 days of no response while in Waiting on Customer status.',
    category: 'customer_followup',
    trigger: 'no_customer_response',
    ruleType: 'timed' as const,
    timeConfig: { delayMinutes: 4320, maxExecutionsPerTicket: 3, repeatIntervalMinutes: 4320, businessHoursOnly: false },
    conditionsLogic: { logic: 'and' as const, groups: [{ logic: 'and' as const, conditions: [{ field: 'status', operator: 'equals', value: 'waiting_on_customer' }] }] },
    actions: [
      { type: 'add_public_reply', params: { message: 'Hi, we are still waiting for your response on this ticket. Please reply at your earliest convenience so we can continue assisting you.' } },
      { type: 'send_notification', params: { message: 'Customer reminder sent for ticket #{ticket_number}' } },
    ],
    exitConditions: [{ field: 'status', operator: 'not_equals', value: 'waiting_on_customer' }],
  },
  {
    id: 'tpl-auto-close-warning',
    name: 'Auto-Close Warning (7 Days)',
    description: 'After 7 days with no customer response, change status to pending and notify customer of upcoming closure.',
    category: 'lifecycle',
    trigger: 'no_customer_response',
    ruleType: 'timed' as const,
    timeConfig: { delayMinutes: 10080, maxExecutionsPerTicket: 1 },
    conditionsLogic: { logic: 'and' as const, groups: [{ logic: 'and' as const, conditions: [{ field: 'status', operator: 'equals', value: 'waiting_on_customer' }] }] },
    actions: [
      { type: 'set_status', params: { status: 'pending' } },
      { type: 'add_public_reply', params: { message: 'This ticket will be automatically closed in 3 days due to inactivity. If you still need assistance, please reply to keep it open.' } },
    ],
    exitConditions: [{ field: 'status', operator: 'not_in', value: 'waiting_on_customer,pending' }],
  },
  {
    id: 'tpl-auto-close',
    name: 'Auto-Close Inactive Tickets (10 Days)',
    description: 'Close tickets that have been inactive for 10+ days (7 days waiting + 3 days pending).',
    category: 'lifecycle',
    trigger: 'ticket_in_status',
    ruleType: 'timed' as const,
    timeConfig: { delayMinutes: 4320, maxExecutionsPerTicket: 1 },
    conditionsLogic: { logic: 'and' as const, groups: [{ logic: 'and' as const, conditions: [{ field: 'status', operator: 'equals', value: 'pending' }] }] },
    actions: [
      { type: 'add_public_reply', params: { message: 'This ticket has been closed due to inactivity. If you need further assistance, please reply to reopen or create a new ticket.' } },
      { type: 'add_internal_note', params: { message: 'Auto-closed by workflow rule after customer inactivity.' } },
      { type: 'close_ticket', params: {} },
    ],
    exitConditions: [],
  },
  {
    id: 'tpl-sla-escalation',
    name: 'SLA Breach Escalation',
    description: 'When SLA is about to breach, escalate ticket priority and notify assigned technician.',
    category: 'sla',
    trigger: 'sla_warning',
    ruleType: 'timed' as const,
    timeConfig: { delayMinutes: 30, maxExecutionsPerTicket: 1 },
    conditionsLogic: { logic: 'and' as const, groups: [{ logic: 'and' as const, conditions: [{ field: 'status', operator: 'not_in', value: 'resolved,closed' }] }] },
    actions: [
      { type: 'escalate_ticket', params: {} },
      { type: 'send_notification', params: { message: 'SLA breach approaching for ticket #{ticket_number}: {ticket_subject}. Please prioritize.' } },
      { type: 'add_internal_note', params: { message: 'SLA escalation triggered — priority increased by workflow automation.' } },
    ],
    exitConditions: [{ field: 'status', operator: 'in', value: 'resolved,closed' }],
  },
  {
    id: 'tpl-vip-priority',
    name: 'VIP Client Priority Boost',
    description: 'Automatically set priority to high for tickets from customers with a premium SLA policy.',
    category: 'escalation',
    trigger: 'ticket_created',
    ruleType: 'instant' as const,
    timeConfig: {},
    conditionsLogic: { logic: 'and' as const, groups: [{ logic: 'and' as const, conditions: [{ field: 'priority', operator: 'in', value: 'low,medium' }, { field: 'slaPolicyId', operator: 'is_not_empty', value: '' }] }] },
    actions: [
      { type: 'set_priority', params: { priority: 'high' } },
      { type: 'add_internal_note', params: { message: 'Priority boosted to High — VIP/Premium SLA customer.' } },
    ],
    exitConditions: [],
  },
  {
    id: 'tpl-after-hours-alert',
    name: 'After-Hours Critical Alert',
    description: 'Send immediate notification when critical tickets are created outside business hours.',
    category: 'escalation',
    trigger: 'ticket_created',
    ruleType: 'instant' as const,
    timeConfig: {},
    conditionsLogic: { logic: 'and' as const, groups: [{ logic: 'and' as const, conditions: [{ field: 'priority', operator: 'equals', value: 'critical' }] }] },
    actions: [
      { type: 'send_notification', params: { message: 'CRITICAL ticket created: #{ticket_number} — {ticket_subject}' } },
      { type: 'notify_manager', params: { message: 'Critical ticket #{ticket_number} requires immediate attention: {ticket_subject}' } },
    ],
    exitConditions: [],
  },
  {
    id: 'tpl-stale-ticket-alert',
    name: 'Stale Ticket Alert (No Tech Update)',
    description: 'Alert when a tech has not updated an open ticket for 24 hours.',
    category: 'operations',
    trigger: 'no_tech_update',
    ruleType: 'timed' as const,
    timeConfig: { delayMinutes: 1440, maxExecutionsPerTicket: 3, repeatIntervalMinutes: 1440, businessHoursOnly: true },
    conditionsLogic: { logic: 'and' as const, groups: [{ logic: 'and' as const, conditions: [{ field: 'status', operator: 'in', value: 'open,pending' }, { field: 'assignedTo', operator: 'is_not_empty', value: '' }] }] },
    actions: [
      { type: 'send_notification', params: { message: 'Ticket #{ticket_number} has had no tech update for 24+ hours. Please review.' } },
    ],
    exitConditions: [{ field: 'status', operator: 'in', value: 'resolved,closed,waiting_on_customer' }],
  },
  {
    id: 'tpl-reopen-on-reply',
    name: 'Reopen on Customer Reply',
    description: 'Automatically reopen a resolved/closed ticket when the customer replies.',
    category: 'lifecycle',
    trigger: 'customer_replied',
    ruleType: 'instant' as const,
    timeConfig: {},
    conditionsLogic: { logic: 'and' as const, groups: [{ logic: 'and' as const, conditions: [{ field: 'status', operator: 'in', value: 'resolved,closed' }] }] },
    actions: [
      { type: 'reopen_ticket', params: {} },
      { type: 'add_internal_note', params: { message: 'Ticket reopened automatically — customer replied.' } },
      { type: 'send_notification', params: { message: 'Ticket #{ticket_number} reopened by customer reply.' } },
    ],
    exitConditions: [],
  },
  {
    id: 'tpl-evidence-expiry',
    name: 'Evidence Expiration Alert',
    description: 'Alert when compliance evidence is approaching expiration date',
    category: 'compliance',
    trigger: 'scheduled_check',
    ruleType: 'scheduled' as const,
    timeConfig: { delayMinutes: 1440, maxExecutionsPerTicket: 1 },
    conditionsLogic: { logic: 'and' as const, groups: [{ logic: 'and' as const, conditions: [] }] },
    actions: [
      { type: 'send_notification', params: { message: 'Compliance evidence is approaching its expiration date. Please review and renew the evidence before it expires.' } },
    ],
    exitConditions: [],
  },
  {
    id: 'tpl-training-overdue',
    name: 'Training Overdue Alert',
    description: 'Notify when security awareness or compliance training is past due',
    category: 'compliance',
    trigger: 'scheduled_check',
    ruleType: 'scheduled' as const,
    timeConfig: { delayMinutes: 1440, maxExecutionsPerTicket: 1 },
    conditionsLogic: { logic: 'and' as const, groups: [{ logic: 'and' as const, conditions: [] }] },
    actions: [
      { type: 'send_notification', params: { message: 'Security awareness or compliance training is overdue. Please complete required training immediately to maintain compliance.' } },
    ],
    exitConditions: [],
  },
  {
    id: 'tpl-poam-due',
    name: 'POA&M Due Date Alert',
    description: 'Alert when POA&M remediation items are approaching their scheduled end date',
    category: 'compliance',
    trigger: 'scheduled_check',
    ruleType: 'scheduled' as const,
    timeConfig: { delayMinutes: 1440, maxExecutionsPerTicket: 1 },
    conditionsLogic: { logic: 'and' as const, groups: [{ logic: 'and' as const, conditions: [] }] },
    actions: [
      { type: 'send_notification', params: { message: 'POA&M remediation item is approaching its scheduled end date. Please ensure corrective actions are completed on time.' } },
      { type: 'notify_manager', params: { message: 'POA&M remediation item is approaching its due date and requires management review.' } },
    ],
    exitConditions: [],
  },
  {
    id: 'tpl-vendor-agreement-expiry',
    name: 'Vendor Agreement Expiration Alert',
    description: 'Alert when BAA, MCA, or other vendor agreements are approaching expiration',
    category: 'compliance',
    trigger: 'scheduled_check',
    ruleType: 'scheduled' as const,
    timeConfig: { delayMinutes: 1440, maxExecutionsPerTicket: 1 },
    conditionsLogic: { logic: 'and' as const, groups: [{ logic: 'and' as const, conditions: [] }] },
    actions: [
      { type: 'send_notification', params: { message: 'A vendor agreement (BAA, MCA, or similar) is approaching its expiration date. Please initiate renewal to maintain compliance.' } },
    ],
    exitConditions: [],
  },
  {
    id: 'tpl-personnel-renewal',
    name: 'Personnel Screening Renewal Alert',
    description: 'Alert when background checks or CJIS certifications are approaching expiration',
    category: 'compliance',
    trigger: 'scheduled_check',
    ruleType: 'scheduled' as const,
    timeConfig: { delayMinutes: 1440, maxExecutionsPerTicket: 1 },
    conditionsLogic: { logic: 'and' as const, groups: [{ logic: 'and' as const, conditions: [] }] },
    actions: [
      { type: 'send_notification', params: { message: 'Personnel screening (background check or CJIS certification) is approaching expiration. Please schedule renewal promptly.' } },
      { type: 'notify_manager', params: { message: 'Personnel screening renewal is due soon and requires management attention.' } },
    ],
    exitConditions: [],
  },
  {
    id: 'tpl-assessment-reminder',
    name: 'Compliance Assessment Due Reminder',
    description: 'Remind when a compliance assessment is due for reassessment (annual/quarterly)',
    category: 'compliance',
    trigger: 'scheduled_check',
    ruleType: 'scheduled' as const,
    timeConfig: { delayMinutes: 1440, maxExecutionsPerTicket: 1 },
    conditionsLogic: { logic: 'and' as const, groups: [{ logic: 'and' as const, conditions: [] }] },
    actions: [
      { type: 'send_notification', params: { message: 'A compliance assessment is due for reassessment. Please schedule and complete the assessment to maintain your compliance posture.' } },
    ],
    exitConditions: [],
  },
];
