// CJIS Security Policy v6.0 — built-in framework content.
// Scoped to controls an MSP implements, verifies, or facilitates for a
// law-enforcement client (police department, sheriff, city PD). Purely
// agency-side legal/administrative controls (information exchange agreements,
// FBI/CSA formal audit programs, HR sanctions) are intentionally omitted.
// Control codes are DB upsert keys — never change them.

import type { FrameworkData } from './types.js';

export const CJIS_FRAMEWORK: FrameworkData = {
  key: 'cjis',
  name: 'CJIS Security Policy',
  shortName: 'CJIS',
  version: '6.0',
  description: 'FBI Criminal Justice Information Services Security Policy — establishes minimum security requirements for protecting Criminal Justice Information (CJI).',
  nistMappingEnabled: true,
  contentVersion: 2,
  metadata: { publisher: 'FBI CJIS Division', effectiveDate: '2022-10-01' },
  areas: [
    {
      code: 'PA-1',
      title: 'Information Exchange Agreements',
      description: 'Agreements that govern outsourced handling of CJI, including the management control and outsourcing standards that apply to the MSP itself.',
      controls: [
        {
          code: '5.1.2',
          title: 'Management Control Agreements',
          description: 'Execute a Management Control Agreement (MCA) with any non-criminal-justice entity, including the MSP, before that entity performs IT functions that touch CJI.',
          explanation: 'CJIS 6.0 requires that when a city IT department or private contractor such as an MSP manages systems that store or process CJI, a written MCA places security control of those systems under the criminal justice agency. In plain terms, the agency retains authority over who can administer CJI systems and how, while the MSP does the day-to-day work. The MSP implements this by keeping a signed MCA on file with each law-enforcement client, listing the covered systems and services (RMM management, server administration, backup, help desk). Verification is documentary: confirm the MCA exists, is signed by both parties, is current, and matches the actual service scope.',
          example: 'Compliant — Signed MCA between Rivertown PD and the MSP dated 2025-08-12 covers server administration, RMM, backup, and help desk for all CAD/RMS systems; reviewed against current SOW 2026-05-02, scope matches.',
          nist: 'SA-9',
          type: 'administrative',
        },
        {
          code: '5.1.3',
          title: 'Outsourcing Standards',
          description: 'Ensure all contractors and subcontractors with access to CJI, including MSP staff, meet the same CJIS security requirements as agency personnel.',
          explanation: 'CJIS holds outside IT providers to the identical standard as sworn and civilian agency staff: fingerprint-based background checks, CJIS Security Awareness Training, and signed CJIS Security Addendum certification pages for every technician who can reach CJI systems. For an MSP this means maintaining a roster of which engineers are cleared for each law-enforcement client and blocking un-cleared staff from those RMM device groups and credentials. The personnel screening module tracks fingerprint submissions, clearance dates, and Security Addendum signatures per technician. Verification means matching the cleared-technician roster against actual RMM and Active Directory access for the client.',
          example: 'Partial — 6 of 7 MSP technicians with RMM access to the PD device group have signed Security Addendum pages and completed fingerprinting; 1 new hire (started 2026-05-18) is pending state channeler results and has been excluded from the PD RMM group until cleared.',
          nist: 'SA-9',
          type: 'administrative',
        },
      ],
    },
    {
      code: 'PA-2',
      title: 'Security Awareness Training',
      description: 'CJIS security awareness training content, records, and frequency requirements for all personnel with access to CJI or CJI systems.',
      controls: [
        {
          code: '5.2.1',
          title: 'Awareness Topics',
          description: 'Provide security awareness training that covers CJI handling, incident reporting, password and authenticator security, and threats such as phishing and social engineering.',
          explanation: 'CJIS 6.0 requires role-based security awareness training whose content matches what each person can touch — basic CJI handling rules for records clerks, deeper technical topics for IT staff with privileged access. The MSP typically delivers and tracks this through a managed SAT platform such as Huntress Security Awareness Training, assigning CJIS-relevant modules (CJI handling, media protection, incident reporting, phishing) to all agency users and cleared MSP technicians. Many agencies also use the state CJIS Online portal; the MSP reconciles both sources into one training record per person. Verification pulls the SAT platform completion report and confirms every user with CJI access has completed the required topic set.',
          example: 'Compliant — All 34 PD users assigned the CJIS awareness track in Huntress SAT (CJI handling, phishing, incident reporting, password security); completion report dated 2026-06-01 shows 34/34 complete; 4 MSP techs completed CJIS Online Level 4 training.',
          nist: 'AT-2',
          type: 'administrative',
          auto: 'huntress',
          autoCheck: 'sat_completion',
        },
        {
          code: '5.2.2',
          title: 'Training Records',
          description: 'Document and retain security awareness training records for every person with access to CJI, including completion dates and content covered.',
          explanation: 'Auditors ask for proof, not assertions: CJIS requires retrievable records showing who was trained, on what content, and when. The MSP centralizes this by exporting completion reports from the SAT platform (Huntress) and, where applicable, CJIS Online certificates, and storing them with the client compliance documentation so they survive staff turnover and platform changes. Records should cover agency employees, volunteers and interns with CJI exposure, and cleared MSP technicians. Verification means sampling several users and producing their individual training certificates with dates on demand.',
          example: 'Compliant — Huntress SAT completion exports archived monthly to the client compliance folder; spot-checked 5 random users on 2026-06-10 and produced dated certificates for all 5, including 2 records division clerks and 1 MSP engineer.',
          nist: 'AT-4',
          type: 'administrative',
          auto: 'huntress',
          autoCheck: 'sat_records',
        },
        {
          code: '5.2.3',
          title: 'Training Frequency',
          description: 'Complete security awareness training within six months of initial assignment to duties involving CJI and refresh it at least annually thereafter.',
          explanation: 'CJIS sets two clocks: new personnel must be trained within six months of gaining CJI access, and everyone must complete refresher training every year. Missed refreshers are one of the most common CJIS audit findings, so the MSP automates the cadence — the SAT platform enrolls new users on onboarding and re-assigns the annual module automatically, with overdue alerts routed to the MSP service board. New-hire onboarding checklists for the agency should include SAT assignment on day one so the six-month window is never at risk. Verification compares each user account creation date and last training completion date against the two deadlines.',
          example: 'Non-compliant — 3 of 34 PD users are past their annual refresher due date (oldest overdue 47 days); the 2 officers hired in April 2026 completed initial training within 30 days. Remediation ticket #18342 opened; overdue users re-enrolled with a 2-week deadline.',
          nist: 'AT-2',
          type: 'administrative',
          auto: 'huntress',
          autoCheck: 'sat_frequency',
        },
      ],
    },
    {
      code: 'PA-3',
      title: 'Incident Response',
      description: 'Detection, reporting, handling, evidence preservation, and tracking of security incidents that involve CJI or CJI systems.',
      controls: [
        {
          code: '5.3.1',
          title: 'Reporting',
          description: 'Report security incidents involving CJI promptly through the agency Local Agency Security Officer (LASO) to the state CSA and FBI CJIS Information Security Officer.',
          explanation: 'When CJI is exposed, stolen, or ransomed, CJIS mandates a formal reporting chain: the incident goes to the agency LASO, then up to the state CJIS Systems Agency ISO and ultimately the FBI. The MSP does not report directly to the FBI, but it is almost always the party that detects the incident — via Huntress EDR alerts, SIEM correlation, or SOC escalation — so the incident response runbook for each law-enforcement client must name the LASO, include after-hours contact details, and set a notification deadline measured in hours. The MSP documents each escalation with timestamps to prove the chain was followed. Verification checks that the runbook exists, contacts are current, and any past incidents show timely LASO notification.',
          example: 'Compliant — IR runbook for Rivertown PD names Lt. Marsh as LASO with 24/7 cell contact, reviewed 2026-03-19; the 2025-11 phishing incident shows Huntress SOC alert at 14:02, MSP triage at 14:20, LASO notified at 15:05, all documented in ticket #15221.',
          nist: 'IR-6',
          type: 'administrative',
        },
        {
          code: '5.3.2',
          title: 'Management',
          description: 'Maintain documented incident handling procedures covering preparation, detection, analysis, containment, eradication, and recovery for CJI systems.',
          explanation: 'CJIS requires a real incident handling capability, not just a reporting phone number: written procedures that walk from detection through containment to recovery. For a law-enforcement client the MSP is the operational arm of this capability, so the MSP maintains a client-specific IR plan that maps its tooling to each phase — Huntress EDR for detection and automated host isolation, RMM for containment actions and forensic data pulls, immutable backups for recovery of CAD/RMS servers. The plan must address CJI-specific decisions such as when dispatch terminals can be isolated without endangering officer safety. Verification confirms the plan is current, phase owners are named, and at least one tabletop or real incident has exercised it in the past year.',
          example: 'Compliant — PD-specific IR plan v3.2 covers all six phases with named owners; Huntress host isolation tested on a spare dispatch workstation 2026-04-22; tabletop exercise with the LASO and MSP SOC lead completed 2026-02-10, notes on file.',
          nist: 'IR-4',
          type: 'administrative',
        },
        {
          code: '5.3.3',
          title: 'Evidence Collection',
          description: 'Preserve evidence from security incidents involving CJI and maintain chain of custody suitable for investigation and potential prosecution.',
          explanation: 'Because the client is a criminal justice agency, incident evidence may feed an actual prosecution, so CJIS expects forensically sound handling: disk images and memory captures taken before remediation wipes them, logs exported and hashed, and a chain-of-custody record for every artifact. The MSP builds this into its IR workflow — Huntress and SIEM data is exported and retained, affected drives are imaged or physically preserved rather than immediately re-imaged, and each hand-off is logged with date, person, and purpose. Technicians are trained not to destroy evidence by rushing to rebuild machines. Verification reviews the evidence-handling section of the IR plan and inspects custody records from past incidents or exercises.',
          example: 'Partial — IR plan includes an evidence preservation step and a chain-of-custody form, but the 2025-11 phishing incident shows the affected laptop was re-imaged before a disk image was taken. Corrective action: technicians retrained 2026-01-08; RMM re-image script now requires IR-lead approval for PD assets.',
          nist: 'IR-4',
          type: 'administrative',
        },
        {
          code: '5.3.4',
          title: 'IR Training',
          description: 'Train all personnel with incident response roles for CJI systems on their responsibilities before authorizing access and periodically thereafter.',
          explanation: 'CJIS requires that people named in the incident response plan actually know their roles — the LASO, agency points of contact, and the MSP engineers who will isolate hosts and preserve evidence. The MSP satisfies this by including IR-role training in technician onboarding for law-enforcement clients, running annual refreshers, and inviting agency staff to joint tabletop exercises. Training records are tracked alongside SAT completion so the same evidence trail covers both. Verification cross-references the IR plan roster against training records and confirms every named responder has current training.',
          example: 'Compliant — All 4 MSP responders and the PD LASO listed in IR plan v3.2 completed IR-role training; annual refresher held 2026-02-10 as part of the tabletop; sign-in sheet and slide deck archived in the client compliance folder.',
          nist: 'IR-2',
          type: 'administrative',
        },
        {
          code: '5.3.5',
          title: 'Monitoring',
          description: 'Track and document all security incidents involving CJI systems on an ongoing basis, including type, volume, and remediation cost.',
          explanation: 'CJIS wants agencies to learn from incidents, which requires a running record: every incident logged with category, affected systems, resolution, and lessons learned. The MSP implements this naturally through its PSA ticketing — security incidents for the law-enforcement client are tagged to a dedicated incident category so they can be reported on, trended, and produced at audit time. Quarterly reviews with the agency (or the vCISO service) summarize incident counts and any recurring patterns such as repeated phishing of dispatch staff. Verification pulls the incident register and confirms it is complete against SOC and EDR alert history.',
          example: 'Compliant — PSA security-incident category shows 7 tracked incidents for Rivertown PD in the trailing 12 months, each with root cause and resolution; Q2 2026 review deck presented to the Chief and LASO on 2026-06-20 flagged phishing as the top vector.',
          nist: 'IR-5',
          type: 'administrative',
        },
      ],
    },
    {
      code: 'PA-4',
      title: 'Auditing and Accountability',
      description: 'Audit logging, log content, review, time synchronization, log protection, and retention requirements for CJI systems.',
      controls: [
        {
          code: '5.4.1',
          title: 'Auditable Events',
          description: 'Configure CJI systems to log security-relevant events including successful and failed login attempts, CJI data access, and administrative actions.',
          explanation: 'CJIS 6.0 enumerates the events that must generate audit records on any system that processes CJI: logon success and failure, account and permission changes, attempts to access or modify CJI, and privileged administrative actions. The MSP implements this with Windows advanced audit policy pushed by GPO to CAD/RMS servers and CJI workstations, plus centralized collection into a SIEM or the Huntress SIEM/log management platform so events are not stranded on individual machines. Domain controllers, application servers, and firewalls should all forward their logs. Verification confirms the audit policy is applied on sampled systems and that the required event categories are actually arriving in the log platform.',
          example: 'Compliant — Advanced audit policy GPO applied to all 3 CAD/RMS servers and 12 CJI workstations; Huntress SIEM ingesting logon, account-management, and object-access events; sampled the RMS server 2026-06-14 and confirmed all required categories present.',
          nist: 'AU-2',
          type: 'technical',
          auto: 'huntress',
          autoCheck: 'siem_logging',
        },
        {
          code: '5.4.2',
          title: 'Content of Audit Records',
          description: 'Ensure audit records capture the event type, date and time, source, user or subject identity, and success or failure outcome for each logged event.',
          explanation: 'A log entry is only useful in a CJI investigation if it answers who, what, when, where, and outcome — CJIS requires all five elements in every audit record. In practice, Windows event logs and modern firewall syslog already carry these fields; the MSP job is making sure nothing strips them in transit and that the SIEM parses user identity and source address into searchable fields. Custom or legacy CAD/RMS applications are the usual gap and may need application-level audit configuration from the vendor. Verification samples records in the SIEM for each source type and confirms all five elements are present and parsed.',
          example: 'Partial — Windows and firewall events in Huntress SIEM contain all required fields; the legacy RMS application logs record actions but not source workstation. Vendor ticket opened 2026-05-30 for the audit-detail patch; compensating control: RMS access is restricted to 4 named terminals.',
          nist: 'AU-3',
          type: 'technical',
          auto: 'huntress',
          autoCheck: 'siem_log_content',
        },
        {
          code: '5.4.3',
          title: 'Audit Monitoring',
          description: 'Review and analyze audit records regularly for indications of inappropriate or unusual activity involving CJI systems.',
          explanation: 'Collecting logs is not enough — CJIS requires someone to actually look at them and act on anomalies such as off-hours CJI queries, repeated failed logons, or new admin accounts. Small agencies cannot staff this, so the MSP typically provides it through a managed SOC: Huntress managed detection reviews EDR and SIEM telemetry 24/7, and the MSP supplements with weekly review of authentication and account-change reports for the CJI environment. Findings feed the incident process from PA-3. Verification confirms SOC coverage is active for all CJI assets and that periodic review is evidenced by tickets, review notes, or report sign-offs.',
          example: 'Compliant — Huntress SOC monitoring active on all 15 PD endpoints and 3 servers; weekly auth-anomaly report reviewed by the MSP security team with sign-off logged in the PSA; 2 escalations in Q2 2026, both benign (new detective account, patch-window admin logons).',
          nist: 'AU-6',
          type: 'technical',
          auto: 'huntress',
          autoCheck: 'soc_monitoring',
        },
        {
          code: '5.4.4',
          title: 'Time Stamps',
          description: 'Synchronize system clocks on all CJI systems to an authoritative time source using NTP so audit records carry accurate timestamps.',
          explanation: 'Incident timelines and court-admissible logs fall apart if clocks disagree, so CJIS requires synchronized time across CJI systems. The standard implementation is Windows Time service hierarchy: the PDC emulator syncs to a reliable external NTP source (such as NIST or pool.ntp.org via the firewall), and all domain members sync to the domain. The MSP monitors clock drift through the RMM (N-central) with an automated check that alerts when any device drifts beyond tolerance. Network gear and cameras in CJI areas should sync to the same source. Verification reviews the RMM time-sync monitor status across all CJI assets.',
          example: 'Compliant — N-central NTP drift monitor deployed to all PD servers and workstations; PDC emulator syncs to time.nist.gov; max observed drift 1.4 seconds across 15 devices on 2026-06-14; firewall and switches point at the same source.',
          nist: 'AU-8',
          type: 'technical',
          auto: 'ncentral',
          autoCheck: 'ntp_sync',
        },
        {
          code: '5.4.5',
          title: 'Protection of Audit Info',
          description: 'Protect audit logs and audit tools from unauthorized access, modification, and deletion.',
          explanation: 'Attackers and malicious insiders clear logs to cover their tracks, so CJIS requires audit data to be tamper-resistant. The MSP achieves this primarily by shipping logs off-host in near real time to a SIEM the endpoint users cannot touch — Huntress log management or a hosted SIEM — so a wiped local event log does not destroy the record. Local protections matter too: restrict Manage Auditing and Clear Log rights to a small admin group, and alert on event log cleared events (1102). Access to the SIEM itself is limited to MSP security staff with MFA. Verification checks log-forwarding health, SIEM access lists, and that a test 1102 event triggers an alert.',
          example: 'Compliant — All PD systems forward logs to Huntress SIEM within minutes of generation; only 3 MSP security staff have SIEM access, all with Duo MFA; event 1102 alert rule tested 2026-05-08 and fired correctly.',
          nist: 'AU-9',
          type: 'technical',
        },
        {
          code: '5.4.6',
          title: 'Audit Record Retention',
          description: 'Retain audit records for a minimum of 365 days and ensure they remain retrievable for investigations and audits.',
          explanation: 'CJIS requires at least one year of audit history so that slow-burn incidents and triennial audits can be reconstructed. Local Windows event logs roll over in days or weeks, which is why centralized retention is the only realistic implementation: the MSP configures the SIEM or log platform (Huntress) with a 365-day-or-longer retention policy for the law-enforcement client tenant. Retention must survive the full year in searchable or restorable form, and the MSP should periodically test retrieving records from many months back. Verification confirms the configured retention period and demonstrates retrieval of a record older than six months.',
          example: 'Compliant — Huntress SIEM tenant for Rivertown PD set to 400-day retention; retrieval test on 2026-06-14 pulled authentication events from 2025-09-02 in under a minute; retention setting screenshot archived as evidence.',
          nist: 'AU-11',
          type: 'administrative',
          auto: 'huntress',
          autoCheck: 'log_retention',
        },
      ],
    },
    {
      code: 'PA-5',
      title: 'Access Control',
      description: 'Controls that limit access to CJI systems and data to authorized users, sessions, devices, and network paths.',
      controls: [
        {
          code: '5.5.1',
          title: 'Account Management',
          description: 'Establish formal procedures for creating, modifying, disabling, and removing accounts on CJI systems, with documented authorization for each change.',
          explanation: 'CJIS requires a managed account lifecycle so that only currently authorized people hold credentials to CJI systems — no orphaned accounts for retired officers, no undocumented service accounts. The MSP operationalizes this through its service desk: account creations and terminations for the agency flow through PSA tickets that capture who authorized them, and quarterly account reviews reconcile Active Directory and Microsoft 365 against the current agency roster from the LASO or records supervisor. Automation in M365/Entra flags stale and mismatched accounts. Verification produces the ticket trail for recent account changes and the most recent reconciliation report.',
          example: 'Compliant — All PD account changes in the last 12 months trace to authorized PSA tickets; Q2 2026 review reconciled 41 AD accounts against the city HR roster and found zero orphans; 2 shared legacy accounts from 2024 remain disabled and documented.',
          nist: 'AC-2',
          type: 'administrative',
          auto: 'm365',
          autoCheck: 'account_management',
        },
        {
          code: '5.5.2',
          title: 'Access Enforcement',
          description: 'Configure CJI systems to technically enforce approved authorizations, so users can only reach the data and functions they are permitted to use.',
          explanation: 'Policy on paper must be backed by technical enforcement: file permissions, application role assignments, and conditional access must actually stop an unauthorized user rather than rely on good behavior. For a law-enforcement client the MSP enforces this with NTFS/share ACLs on CJI file stores, security-group-based access to the CAD/RMS application, and Entra Conditional Access policies restricting M365 access to compliant, known devices. Records staff, patrol, and administrative users get distinct group memberships that map to their duties. Verification tests enforcement directly — attempt access to a CJI share with a non-authorized test account and confirm denial, and review Conditional Access policy state.',
          example: 'Compliant — CJI file shares restricted to the SG-PD-CJI security group; test with a city public-works account on 2026-06-14 was denied; Entra Conditional Access blocks M365 access from non-Intune-compliant devices, policy in enforce mode since 2025-10.',
          nist: 'AC-3',
          type: 'technical',
          auto: 'm365',
          autoCheck: 'conditional_access',
        },
        {
          code: '5.5.3',
          title: 'Unsuccessful Login Attempts',
          description: 'Lock user accounts after no more than five consecutive failed login attempts on CJI systems.',
          explanation: 'Account lockout blunts password-guessing attacks against CJI systems, and CJIS sets the threshold at five failed attempts. The MSP enforces this through domain Group Policy (account lockout threshold of 5, with a defined lockout duration or admin-unlock requirement) and the matching Entra smart lockout settings for cloud identities. Dispatch and MDT logins need the same policy — mobile data terminals are a frequent gap. Lockout events (4740) should surface in the SIEM so brute-force attempts are noticed, not just blocked. Verification reads the effective GPO on sampled machines and confirms Entra lockout settings match.',
          example: 'Compliant — Domain GPO sets lockout threshold 5 / duration 30 minutes, verified on 3 sampled workstations and both DCs 2026-06-14; Entra smart lockout at 5; MDT laptops confirmed in-scope via RMM policy report.',
          nist: 'AC-7',
          type: 'technical',
          auto: 'm365',
          autoCheck: 'lockout_policy',
        },
        {
          code: '5.5.4',
          title: 'System Use Notification',
          description: 'Display an approved system use notification banner before granting access to any CJI system, warning that use is monitored and restricted to authorized purposes.',
          explanation: 'CJIS requires that anyone logging into a CJI system first see a banner stating the system is for authorized use only, activity may be monitored, and misuse is subject to penalties — this preserves the legal basis for monitoring and prosecution. The MSP deploys the agency-approved banner text via Group Policy (interactive logon message title and text) to all CJI workstations and servers, and mirrors it on VPN portals and remote access gateways. The RMM monitors that the registry values remain set so a rebuilt machine does not silently lose the banner. Verification is visual and automated: log into a sampled terminal to see the banner, and review the RMM banner-compliance check.',
          example: 'Compliant — CJIS logon banner GPO applied domain-wide; N-central check reports the banner registry keys present on 15/15 PD endpoints; banner also configured on the SSL-VPN portal; visually confirmed on a dispatch terminal 2026-06-14.',
          nist: 'AC-8',
          type: 'technical',
          auto: 'ncentral',
          autoCheck: 'login_banner',
        },
        {
          code: '5.5.5',
          title: 'Session Lock',
          description: 'Automatically lock CJI system sessions after no more than 30 minutes of inactivity, requiring re-authentication to resume.',
          explanation: 'An unattended, unlocked terminal in a records office or squad room is an open door to CJI, so CJIS caps the inactivity timeout at 30 minutes (many agencies choose 10 or 15). The MSP enforces this with a Group Policy screen saver lock or machine inactivity limit across all CJI workstations, and equivalent Intune/MDM policy on laptops and MDTs. Dispatch positions that must stay visible can use approved compensating controls, but the exception must be documented with the CSO. The RMM continuously audits the timeout setting so drift is caught. Verification samples effective policy on desktops, dispatch terminals, and mobile units.',
          example: 'Compliant — GPO enforces a 15-minute lock on all 12 CJI workstations; spot-checked 3 dispatch terminals 2026-06-14; MDT units lock at 15 minutes via Intune; one CAD wall-display machine documented as a CSO-approved exception with physical access controls.',
          nist: 'AC-11',
          type: 'technical',
          auto: 'ncentral',
          autoCheck: 'screen_lock_policy',
        },
        {
          code: '5.5.6',
          title: 'Remote Access',
          description: 'Permit remote access to CJI systems only through encrypted VPN connections protected by multi-factor authentication, with all sessions monitored and controlled.',
          explanation: 'Remote access is the highest-risk path into a CJI environment, covering officers on MDTs, detectives working from home, and MSP technicians themselves. CJIS requires FIPS-validated encryption for the tunnel plus advanced authentication, implemented in practice as an IPsec/SSL VPN with Duo MFA enforced at connection time; MDT fleets commonly ride Cradlepoint or NetMotion tunnels with the same MFA requirement. Critically, the MSP must hold its own remote administration to this standard — RMM access to the agency environment gated by MFA, sessions logged, and no unattended TeamViewer-style backdoors. Verification tests a VPN login to confirm the MFA challenge, reviews VPN cipher configuration, and audits which accounts hold remote-access rights.',
          example: 'Compliant — All remote CJI access rides the Fortinet VPN with Duo MFA (tested 2026-06-12); MDTs use Cradlepoint with certificate + Duo; MSP technician access to the PD environment requires Duo on both the RMM and the VPN; 0 accounts with VPN rights outside the approved group.',
          nist: 'AC-17',
          type: 'technical',
          severity: 'high',
        },
        {
          code: '5.5.7',
          title: 'Wireless Access',
          description: 'Apply additional protections to any wireless network that carries CJI, including strong encryption, authentication, and separation from guest and public networks.',
          explanation: 'Wireless is treated as hostile territory in CJIS: any Wi-Fi that touches CJI must use strong modern encryption and authentication, and untrusted wireless (guest networks, public hotspots) must be fully segmented away from CJI systems. The MSP implements this with WPA2-Enterprise or WPA3 using 802.1X certificate or RADIUS authentication on the agency SSID, a VLAN-isolated guest network with no route to CJI subnets, and firewall rules enforcing the separation. Rogue access point detection through the wireless controller or periodic scans closes the gap of unauthorized APs plugged in by staff. Verification reviews controller configuration, firewall rules between wireless and CJI VLANs, and recent rogue-AP scan results.',
          example: 'Partial — PD staff SSID uses WPA2-Enterprise with RADIUS against AD and guest Wi-Fi is VLAN-isolated (rules verified 2026-06-10), but rogue-AP scanning is manual and last ran 2026-01-15. Remediation: enabling scheduled rogue detection on the UniFi controller, ticket #18455.',
          nist: 'AC-18',
          type: 'technical',
        },
        {
          code: '5.5.8',
          title: 'Mobile Device Access',
          description: 'Manage every mobile device that can access CJI through mobile device management with enforced security policies before access is granted.',
          explanation: 'Smartphones and tablets used by officers and command staff routinely receive CJI through email, CAD apps, or records portals, so CJIS requires MDM enrollment as a precondition of access. The MSP enrolls agency devices in Intune or an equivalent MDM and enforces a baseline: device encryption, PIN/biometric lock, remote wipe, OS version minimums, and blocking of jailbroken devices. Conditional Access ties it together by refusing M365/CJI application access from unenrolled or non-compliant devices, making the control self-enforcing. Verification pulls the MDM compliance report and confirms Conditional Access blocks a test unenrolled device.',
          example: 'Compliant — 22 agency phones enrolled in Intune with encryption, 6-digit PIN, and remote wipe enforced; Entra Conditional Access blocks unenrolled devices (tested with a personal phone 2026-05-27, access denied); 1 non-compliant device auto-quarantined and remediated within 24 hours.',
          nist: 'AC-19',
          type: 'technical',
        },
        {
          code: '5.5.9',
          title: 'Least Privilege',
          description: 'Grant each user and process only the minimum access to CJI systems necessary to perform assigned duties.',
          explanation: 'CJIS applies the least-privilege principle to blunt both insider misuse and the blast radius of a compromised account: a records clerk does not need domain admin, and an officer does not need access to internal-affairs case files. The MSP implements this with tiered administration (separate day-to-day and admin accounts for IT staff, including its own technicians), removal of local admin rights from end users, and scoped permissions on CJI shares and applications. Privileged access reviews run at least annually, and tools in M365/Entra flag over-privileged accounts. Verification enumerates members of Domain Admins and other privileged groups and checks that each membership has a documented justification.',
          example: 'Compliant — Domain Admins contains 3 accounts, all MSP tier-0 admin accounts with Duo MFA; 0 PD end users have local admin (removed 2025-09 via RMM policy); annual privileged access review completed 2026-04-30 and removed 2 stale delegations.',
          nist: 'AC-6',
          type: 'administrative',
          auto: 'm365',
          autoCheck: 'least_privilege',
        },
        {
          code: '5.5.10',
          title: 'Role-Based Access',
          description: 'Assign access to CJI systems through defined roles that map job functions to specific permissions, rather than granting rights to individuals ad hoc.',
          explanation: 'Role-based access control makes least privilege sustainable: instead of hand-crafting permissions per person, the agency defines roles — patrol officer, detective, records clerk, dispatcher, command staff, IT admin — and each role carries a fixed permission set. The MSP implements this as Active Directory and Entra security groups mapped to those roles, with CJI application access (CAD, RMS, file shares) granted only via group membership. Onboarding and transfers then become a single group change, which the account management process in 5.5.1 documents. Verification confirms that direct user-level permissions are absent from CJI resources and that the role-to-group matrix is documented and current.',
          example: 'Compliant — Role matrix (6 roles) documented in the client runbook, last updated 2026-03-02; CJI shares and RMS access granted exclusively through role groups; ACL audit on 2026-06-14 found 0 direct user grants on CJI resources.',
          nist: 'AC-3',
          type: 'administrative',
        },
      ],
    },
    {
      code: 'PA-6',
      title: 'Identification and Authentication',
      description: 'Requirements for uniquely identifying users and authenticating them to CJI systems, including passwords, MFA, and identifier lifecycle management.',
      controls: [
        {
          code: '5.6.1',
          title: 'Unique Identification',
          description: 'Assign every user of a CJI system a unique identifier and prohibit shared or group accounts for CJI access.',
          explanation: 'Accountability in a criminal justice environment depends on knowing exactly who ran a query or opened a record, which shared logins destroy. CJIS therefore requires a unique account per person on every CJI system, including dispatch consoles and MDTs where shared "position" logins are a common legacy practice. The MSP audits Active Directory, M365, and the CAD/RMS application for generic accounts (dispatch1, records, frontdesk) and works with the agency to replace them with individual credentials, converting any unavoidable service accounts to documented, non-interactive use. Automated checks in M365 flag accounts with shared-mailbox or generic naming patterns that hold sign-in ability. Verification lists all enabled accounts and confirms each maps to one named person or a documented service function.',
          example: 'Partial — 39 of 41 AD accounts map to named individuals; 2 legacy shared dispatch logins remain on the old CAD pending the Q3 2026 CAD upgrade that supports individual logins; interim compensating control documented (physical access limits + camera coverage of dispatch).',
          nist: 'IA-4',
          type: 'administrative',
          auto: 'm365',
          autoCheck: 'unique_accounts',
        },
        {
          code: '5.6.2',
          title: 'Authentication Policy',
          description: 'Document an authentication policy that defines the approved authenticator types, strength requirements, and procedures for all CJI system access.',
          explanation: 'CJIS expects the rules for how users prove identity to be written down, approved, and kept current — covering password standards, where MFA is mandatory, how authenticators are issued and reset, and how the requirements map to CJIS 6.0 identity assurance levels. The MSP typically drafts or maintains this policy for the law-enforcement client as part of its vCISO/compliance service, keeping it aligned with what is actually enforced by Group Policy, Entra, and Duo so the paper and the configuration never diverge. The policy also governs MSP technician authentication to agency systems. Verification confirms the document exists, is dated within its review cycle, is signed by agency leadership, and matches enforced settings.',
          example: 'Compliant — Rivertown PD Authentication Policy v2.1 approved by the Chief 2026-01-15, defines password standards, Duo MFA scope, and reset procedures; side-by-side check against the enforced GPO and Duo policies on 2026-06-10 found no gaps.',
          nist: 'IA-1',
          type: 'administrative',
        },
        {
          code: '5.6.3',
          title: 'Standard Authentication',
          description: 'Enforce password standards on CJI systems meeting CJIS requirements for minimum length, complexity, and change or compromise-handling rules.',
          explanation: 'CJIS 6.0 modernized password rules toward NIST 800-63: longer passwords screened against known-breached lists are favored, while the legacy baseline (8+ characters, complexity, 90-day expiration) remains the floor for agencies that have not adopted the advanced option. The MSP enforces whichever standard the agency has adopted via domain Group Policy or Entra password policy, and where possible adds Entra Password Protection or an equivalent banned-password screen. MDTs, the CAD/RMS application, and network gear must follow the same standard, not just Windows logins. Verification reads the effective password policy from the domain and Entra and compares it to the documented authentication policy.',
          example: 'Compliant — Domain policy enforces 14-character minimum with Entra Password Protection banned-word screening (agency adopted the 800-63 style standard, so periodic expiration is disabled per policy v2.1); RMS application minimums raised to match 2026-02-19; verified via GPO report 2026-06-14.',
          nist: 'IA-5',
          type: 'technical',
          auto: 'm365',
          autoCheck: 'password_policy',
        },
        {
          code: '5.6.4',
          title: 'Advanced Authentication (MFA)',
          description: 'Require multi-factor authentication for all remote access to CJI and for access from non-secure locations or with elevated privileges.',
          explanation: 'This is the highest-profile CJIS technical control: password-only access to CJI from outside a physically secure location is prohibited, and CJIS 6.0 expands MFA expectations broadly across CJI access. The MSP implements it with Duo MFA in front of the VPN, remote desktop gateways, M365/Entra sign-in, and privileged admin logons, with FIDO2 keys or Duo push (number-matching, phishing-resistant options preferred) as the second factor. MDT logins from vehicles count as remote access and must be covered, as must MSP technician access to the agency environment. Enrollment gaps are the usual audit finding, so Duo enrollment status is monitored continuously. Verification pulls the Duo enrollment report against the full user list and tests that unenrolled access paths are actually blocked.',
          example: 'Compliant — Duo enforced on VPN, RD Gateway, M365, and admin logons; enrollment report 2026-06-14 shows 41/41 active PD users and 4/4 MSP techs enrolled; new-user policy blocks access until enrollment; MDT logins verified to prompt Duo via the Cradlepoint VPN.',
          nist: 'IA-2',
          type: 'technical',
          severity: 'critical',
          auto: 'duo',
          autoCheck: 'mfa_enrolled',
        },
        {
          code: '5.6.5',
          title: 'Identifier Management',
          description: 'Manage user identifiers over their lifecycle and disable any account after 90 days of inactivity on CJI systems.',
          explanation: 'Dormant accounts of retired officers, seasonal staff, or departed contractors are prime targets because nobody notices when they get abused, so CJIS mandates disabling identifiers after 90 days without use. The MSP automates this with a scheduled report or script against Active Directory and Entra last-logon data, auto-disabling or ticketing accounts that cross the threshold, with documented exceptions for legitimate cases such as military leave. The check must also cover the CAD/RMS application and VPN accounts, which often have separate identity stores. Verification runs the inactivity report and confirms no enabled account exceeds 90 days idle without an approved exception.',
          example: 'Compliant — Weekly automated inactivity report from Entra and AD; 2026-06-14 run shows 0 enabled accounts idle over 90 days; 1 exception on file (officer on military deployment, approved by the Chief 2026-03-01, account disabled but retained).',
          nist: 'IA-4',
          type: 'administrative',
          auto: 'm365',
          autoCheck: 'inactive_accounts',
        },
        {
          code: '5.6.6',
          title: 'Authenticator Management',
          description: 'Establish procedures for issuing, storing, resetting, and revoking authenticators such as passwords, tokens, and certificates for CJI systems.',
          explanation: 'CJIS requires the whole lifecycle of authenticators to be controlled: initial credentials delivered securely and changed on first use, help-desk resets that verify caller identity before acting (defeating the social-engineering resets behind many breaches), immediate revocation at separation, and secure storage of any secrets the MSP holds. The MSP implements identity-verification scripts for its service desk (callback to a known number, supervisor confirmation, or video check for the agency), stores privileged credentials for the client in a vaulted password manager with per-technician access and audit logs, and manages Duo token/passkey issuance and revocation. Verification reviews the reset procedure, samples recent reset tickets for identity-verification evidence, and audits vault access logs.',
          example: 'Partial — Credential vault (with per-tech Duo MFA and access logging) and revocation-at-termination process verified; however, 2 of 10 sampled password-reset tickets from May 2026 lacked recorded identity verification. Service desk retrained 2026-06-05 and the PSA ticket template now requires a verification-method field.',
          nist: 'IA-5',
          type: 'administrative',
        },
        {
          code: '5.6.7',
          title: 'Authenticator Feedback',
          description: 'Obscure authentication feedback so passwords and other secrets are masked during entry on CJI systems.',
          explanation: 'Systems must not echo passwords to the screen where a shoulder-surfer in a busy dispatch center or public counter could read them — masking with dots or asterisks is the required behavior. Modern Windows, M365, VPN clients, and mainstream CAD/RMS software mask by default, so the MSP effort is mostly assurance: confirm no legacy or custom application used for CJI displays credentials in cleartext, and that any "show password" toggles require deliberate user action. Kiosk and shared-area terminals deserve particular attention since exposure risk is highest there. Verification is a quick walkthrough of each CJI login surface confirming masked entry.',
          example: 'Compliant — Login surfaces for Windows, RMS, CAD, VPN client, and M365 all mask password entry; walkthrough completed 2026-06-14 including the records-counter terminal; no cleartext credential display found.',
          nist: 'IA-6',
          type: 'technical',
        },
      ],
    },
  ],
};
