// CMMC Level 2 (NIST SP 800-171 Rev 2) framework content.
// Source of truth for the built-in CMMC framework; synced to the DB by shortName / area code / control code.
// Control codes, NIST mappings, type, severity, and automation keys must never change — they are upsert keys
// and automation bindings. Prose fields (description/explanation/example) may be revised; bump contentVersion.

import type { FrameworkData } from './types.js';

export const CMMC_FRAMEWORK: FrameworkData = {
  key: 'cmmc',
  name: 'CMMC Level 2 (NIST 800-171)',
  shortName: 'CMMC',
  version: '2.0',
  description: 'Cybersecurity Maturity Model Certification Level 2 — protects Controlled Unclassified Information (CUI) based on NIST SP 800-171 Rev 2.',
  nistMappingEnabled: true,
  contentVersion: 2,
  metadata: { publisher: 'US Department of Defense', effectiveDate: '2024-12-16' },
  areas: [
    {
      code: 'AC',
      title: 'Access Control',
      description: 'Limits system and network access to authorized users, processes, and devices, and governs how CUI is allowed to flow between them.',
      controls: [
        {
          code: 'AC.L2-3.1.1',
          title: 'Authorized Access Control',
          description: 'Limit system access to authorized users, processes acting on behalf of authorized users, and authorized devices.',
          explanation: 'Every account, service principal, and device that can touch systems holding CUI must be explicitly authorized and tracked. For a small defense contractor this means a documented account list in Entra ID (ideally M365 GCC High), unique named accounts for every employee, and prompt deprovisioning when people leave. The MSP typically enforces this through Entra ID account lifecycle management, RMM asset inventory to catch unknown devices, and conditional access policies that block unmanaged endpoints. An assessor verifies it by comparing the active account list against the HR roster and reviewing deprovisioning tickets for recent departures.',
          example: 'Compliant — All 22 active Entra ID accounts reconciled against HR roster on 2026-06-15; two terminated users disabled within 4 business hours per offboarding tickets #4411 and #4520; conditional access blocks sign-in from non-Intune-enrolled devices.',
          nist: 'AC-2',
          type: 'technical',
          auto: 'm365',
          autoCheck: 'account_management',
        },
        {
          code: 'AC.L2-3.1.2',
          title: 'Transaction & Function Control',
          description: 'Limit system access to the types of transactions and functions that authorized users are permitted to execute.',
          explanation: 'Beyond simply logging in, users should only be able to perform the actions their role requires — a shop-floor user should not be able to export the entire contracts SharePoint library. The MSP implements this with role-based permissions in M365 (SharePoint site roles, security groups), NTFS permissions on file servers, and application-level roles in ERP or accounting systems. Admin functions are separated into dedicated privileged accounts. Assessors verify by sampling users and confirming their effective permissions match a documented role matrix.',
          example: 'Partial — SharePoint CUI library permissions align with the documented role matrix, but three users in the Estimating group retain write access to the Contracts library from a 2024 project; remediation ticket #5102 opened to remove excess access.',
          nist: 'AC-3',
          type: 'technical',
        },
        {
          code: 'AC.L2-3.1.3',
          title: 'CUI Flow Control',
          description: 'Control the flow of CUI in accordance with approved authorizations.',
          explanation: 'The organization must define where CUI is allowed to live and move — for example, only within the GCC High tenant and the designated file server — and enforce those boundaries technically. MSPs implement flow control with DLP policies in Microsoft Purview, mail transport rules that block CUI to external recipients, firewall segmentation, and blocking consumer cloud storage (Dropbox, personal OneDrive) on managed endpoints. A data flow diagram in the SSP shows approved paths. Assessors verify by reviewing the diagram, testing a DLP rule, and checking that unsanctioned egress paths are blocked.',
          example: 'Compliant — CUI scoped to GCC High tenant and FS01 per SSP data flow diagram v3.1; Purview DLP policy blocks outbound email containing CUI markings (test message blocked 2026-05-28); consumer cloud storage domains blocked at the DNS filter.',
          nist: 'AC-4',
          type: 'technical',
        },
        {
          code: 'AC.L2-3.1.5',
          title: 'Least Privilege',
          description: 'Employ the principle of least privilege, including for specific security functions and privileged accounts.',
          explanation: 'Users and administrators get the minimum rights needed to do their jobs — no standing Domain Admin for daily work and no local admin for regular users. The MSP implements this by removing local admin rights via RMM policy, issuing separate admin accounts for the one or two staff who need them, and using Entra ID role assignments (or PIM in GCC High) scoped to specific duties. Quarterly access reviews keep entitlements from drifting. Assessors verify by enumerating privileged group membership and asking for the business justification for each member.',
          example: 'Compliant — Local admin removed from all 34 workstations via RMM policy; two named admin accounts (jsmith-adm, MSP break-glass) are the only members of Domain Admins; Q2 2026 access review completed 2026-06-20 with sign-off from the ISSO.',
          nist: 'AC-6',
          type: 'administrative',
        },
        {
          code: 'AC.L2-3.1.6',
          title: 'Non-Privileged Account Use',
          description: 'Use non-privileged accounts or roles when accessing non-security functions.',
          explanation: 'Administrators must do email, browsing, and daily work from a standard account and only elevate with a separate admin identity when performing administrative tasks. This limits the blast radius when a phishing email lands in an admin mailbox. The MSP enforces it by issuing paired accounts (user + -adm), blocking mailbox and Office licensing on admin accounts, and using conditional access to restrict where admin accounts can sign in. Assessors verify by checking that admin accounts have no mailbox and reviewing sign-in logs for evidence of daily-driver use.',
          example: 'Compliant — Both IT admin users hold separate -adm accounts with no M365 license or mailbox; Entra sign-in logs for May 2026 show admin accounts used only for portal and server RDP sessions.',
          nist: 'AC-6(2)',
          type: 'technical',
        },
        {
          code: 'AC.L2-3.1.7',
          title: 'Privileged Functions',
          description: 'Prevent non-privileged users from executing privileged functions and capture the execution of such functions in audit logs.',
          explanation: 'Standard users must be technically blocked from actions like installing software, changing security settings, or clearing logs, and any privileged action must leave an audit trail. The MSP implements this with UAC enforced via GPO/Intune, removal of local admin rights, and Windows event auditing (4672, 4688) forwarded to the SIEM or Huntress-managed logging. Attempts by non-privileged users to elevate should fail and be logged. Assessors verify by attempting a privileged action as a standard user and pulling the corresponding audit events.',
          example: 'Compliant — Test standard user blocked from installing software and stopping the Huntress service on 2026-06-11; privilege-use auditing (event 4672/4688) enabled via GPO and forwarded to the managed SIEM with 12-month retention.',
          nist: 'AC-6(9)',
          type: 'technical',
        },
        {
          code: 'AC.L2-3.1.8',
          title: 'Unsuccessful Logon Attempts',
          description: 'Limit the number of unsuccessful logon attempts before an account is locked or delayed.',
          explanation: 'Account lockout thresholds slow down password guessing and spraying attacks against both local and cloud logons. Typical MSP configuration is an AD lockout policy of 5-10 failed attempts with a 15-30 minute lockout, plus Entra ID Smart Lockout in the M365 tenant. The setting is deployed by GPO or Intune and monitored for drift by the RMM. Assessors verify by reviewing the effective policy on a sampled workstation and the Entra ID authentication settings.',
          example: 'Compliant — AD lockout policy set to 6 attempts / 30-minute lockout via Default Domain Policy; Entra Smart Lockout at default 10 attempts; effective policy confirmed on sampled workstation WKS-014 on 2026-06-11.',
          nist: 'AC-7',
          type: 'technical',
          auto: 'm365',
          autoCheck: 'lockout_policy',
        },
        {
          code: 'AC.L2-3.1.9',
          title: 'Privacy & Security Notices',
          description: 'Provide privacy and security notices consistent with applicable CUI rules at system logon.',
          explanation: 'Systems that process CUI must display a logon banner informing users that use is monitored and subject to CUI handling rules, which supports later disciplinary or legal action. The MSP deploys the interactive logon banner text via GPO or Intune configuration profile to all managed Windows endpoints and servers, and adds equivalent notices to VPN and remote-access portals. Banner wording is approved by the client and recorded in policy. Assessors verify by observing the banner at logon on sampled systems and comparing the text to the approved policy language.',
          example: 'Compliant — DoD-style CUI logon banner deployed via GPO to all domain systems and via Intune to 6 Entra-only laptops; banner observed at logon on WKS-003 and SRV-FS01 during the 2026-06-12 walkthrough.',
          nist: 'AC-8',
          type: 'technical',
          auto: 'ncentral',
          autoCheck: 'login_banner',
        },
        {
          code: 'AC.L2-3.1.10',
          title: 'Session Lock',
          description: 'Use session lock with pattern-hiding displays to prevent access and viewing of data after a period of inactivity.',
          explanation: 'Unattended workstations must lock automatically and show a screen that hides whatever was on the display, so CUI is not readable to passersby. The MSP enforces an inactivity screen lock (typically 10-15 minutes) with password-protected screensaver or Windows lock via GPO/Intune, monitored for compliance by the RMM. Shop-floor or shared kiosks with CUI access need shorter timeouts. Assessors verify by checking the effective timeout on sampled machines and watching a machine lock during the walkthrough.',
          example: 'Compliant — 15-minute inactivity lock with blank screen enforced via Intune on all 34 endpoints; RMM policy check shows 34/34 compliant as of 2026-06-30; lock behavior demonstrated on a sampled laptop.',
          nist: 'AC-11',
          type: 'technical',
          auto: 'ncentral',
          autoCheck: 'screen_lock_policy',
        },
        {
          code: 'AC.L2-3.1.11',
          title: 'Session Termination',
          description: 'Terminate user sessions automatically after a defined condition or period of inactivity.',
          explanation: 'Unlike a screen lock, this requires that sessions actually end — RDP sessions, VPN tunnels, and web app sessions must be disconnected and logged off after a defined idle period. The MSP configures RDP session time limits via GPO, VPN idle timeouts on the firewall, and M365/Entra sign-in session policies with conditional access. Defined limits are documented in the SSP. Assessors verify by reviewing the configured timeout values and observing or testing a forced disconnect.',
          example: 'Partial — RDP sessions on servers disconnect after 30 minutes idle and log off after 2 hours per GPO, and VPN idle timeout is 60 minutes; however, the ERP web application has no session timeout configured — POA&M item 2026-07 opened with vendor.',
          nist: 'AC-12',
          type: 'technical',
        },
        {
          code: 'AC.L2-3.1.12',
          title: 'Remote Access Control',
          description: 'Monitor and control all remote access sessions to organizational systems.',
          explanation: 'Every remote path into the environment — VPN, RDP gateways, and the MSP remote-control tool itself — must be authorized, authenticated with MFA, logged, and reviewable. The MSP implements this with a firewall VPN requiring Duo MFA, RMM remote sessions that log technician, endpoint, and duration, and blocking of unsanctioned tools like consumer TeamViewer or AnyDesk. Session logs are retained and periodically reviewed. Assessors verify by reviewing the remote access inventory in the SSP, VPN and RMM session logs, and evidence that rogue remote tools are blocked.',
          example: 'Compliant — Remote access limited to Fortinet VPN with Duo MFA and N-central remote control; both log all sessions (samples from June 2026 reviewed); unauthorized remote tools blocked by Huntress-managed application control with two blocked AnyDesk attempts alerted in May.',
          nist: 'AC-17',
          type: 'technical',
        },
        {
          code: 'AC.L2-3.1.14',
          title: 'Remote Access Routing',
          description: 'Route all remote access through managed access control points.',
          explanation: 'Remote connections must funnel through a small number of controlled chokepoints — typically the firewall VPN concentrator or a hardened RD Gateway — rather than direct exposed RDP or per-machine tunnels. This lets the organization apply MFA, logging, and policy in one place. The MSP verifies no servers or workstations expose RDP/SSH directly to the internet (external scans via Nodeware or similar) and documents the approved access points in the SSP. Assessors verify with an external port scan and firewall rule review.',
          example: 'Compliant — All remote access routes through the FortiGate VPN; external Nodeware scan 2026-06-05 shows no exposed RDP/SMB/SSH; firewall rulebase reviewed and no inbound NAT rules to internal hosts exist.',
          nist: 'AC-17(3)',
          type: 'technical',
        },
        {
          code: 'AC.L2-3.1.15',
          title: 'Privileged Remote Access',
          description: 'Authorize remote execution of privileged commands and remote access to security-relevant information.',
          explanation: 'Performing administrative work remotely — server administration over VPN, RMM scripting, firewall management — must be explicitly authorized, limited to named individuals, and logged. For an MSP-managed client this is largely about governing the MSP itself: the managed services agreement and SSP name which technicians may perform privileged remote work and through which tools. Privileged remote sessions require MFA and generate audit records in the RMM and VPN logs. Assessors verify by reviewing the authorization documentation and sampling privileged session logs against the authorized personnel list.',
          example: 'Compliant — SSP section 9 authorizes 4 named MSP technicians for privileged remote administration via N-central and VPN with Duo MFA; June 2026 RMM session log sampled and all privileged sessions map to authorized technicians.',
          nist: 'AC-17(4)',
          type: 'administrative',
        },
        {
          code: 'AC.L2-3.1.16',
          title: 'Wireless Access Authorization',
          description: 'Authorize wireless access to organizational systems before allowing such connections.',
          explanation: 'Wireless networks that can reach CUI systems must be deliberately designed and approved, not ad hoc — including which SSIDs exist, who may join them, and how guest traffic is isolated. The MSP documents the wireless architecture in the SSP, configures the corporate SSID for managed devices only, and places guest wireless on an isolated VLAN with no route to internal systems. Rogue access point detection is enabled on managed APs. Assessors verify by reviewing the wireless documentation and controller configuration and confirming guest isolation.',
          example: 'Compliant — Two SSIDs on Meraki: corporate (restricted to Intune-managed devices) and guest (isolated VLAN, no internal routes); wireless design approved in SSP v3.1; rogue AP detection enabled with alerts to the MSP.',
          nist: 'AC-18',
          type: 'technical',
        },
        {
          code: 'AC.L2-3.1.17',
          title: 'Wireless Access Protection',
          description: 'Protect wireless access using authentication and encryption.',
          explanation: 'Corporate wireless must use strong modern encryption (WPA2-Enterprise or WPA3) and authenticate users or devices — certificate-based 802.1X is the gold standard, and at minimum a strong WPA2/WPA3 passphrase rotated when staff leave. The MSP configures RADIUS/802.1X against Entra ID or NPS where feasible, disables WPS and legacy protocols (WEP, WPA-TKIP), and manages AP firmware through the RMM or cloud controller. Assessors verify by reviewing controller settings and confirming no legacy encryption is in use.',
          example: 'Partial — Corporate SSID uses WPA2-Enterprise with certificate auth via NPS; however, a legacy warehouse SSID still uses a WPA2-PSK unchanged since 2023 with two former employees who knew it — passphrase rotation and migration to 802.1X scheduled for 2026-07-15.',
          nist: 'AC-18(1)',
          type: 'technical',
        },
        {
          code: 'AC.L2-3.1.18',
          title: 'Mobile Device Connection',
          description: 'Control the connection of mobile devices to organizational systems.',
          explanation: 'Phones and tablets that access company email or CUI must be enrolled and governed — unmanaged personal devices cannot be allowed to sync CUI freely. The MSP implements this with Intune MDM or MAM app-protection policies (mandatory in GCC High scenarios), conditional access that blocks unenrolled devices from M365, and enforced device PIN and encryption. A mobile device policy defines what BYOD may and may not access. Assessors verify by reviewing conditional access policies, the Intune enrollment list, and a test connection attempt from an unmanaged device.',
          example: 'Compliant — Conditional access requires Intune compliance for mobile access to M365; 19 enrolled devices all show compliant; test sign-in from an unenrolled phone blocked on 2026-06-11; BYOD limited to Outlook with MAM app protection.',
          nist: 'AC-19',
          type: 'technical',
          severity: 'high',
        },
        {
          code: 'AC.L2-3.1.19',
          title: 'Encrypt CUI on Mobile',
          description: 'Encrypt CUI stored on mobile devices and mobile computing platforms.',
          explanation: 'Laptops, phones, and tablets that may hold CUI must have full storage encryption so a lost device does not become a reportable CUI spill. The MSP enforces BitLocker on all Windows laptops via Intune or GPO with recovery keys escrowed to Entra ID/AD, and requires device encryption via Intune compliance policy on iOS/Android. The RMM continuously reports encryption status so gaps are caught quickly. Assessors verify by sampling the encryption compliance report and checking recovery key escrow.',
          example: 'Compliant — BitLocker (XTS-AES 256) enforced on all 21 laptops with keys escrowed to Entra ID; RMM encryption report 2026-06-30 shows 21/21 encrypted; iOS/Android compliance policy requires device encryption and all 19 mobile devices compliant.',
          nist: 'AC-19(5)',
          type: 'technical',
          severity: 'critical',
          auto: 'ncentral',
          autoCheck: 'disk_encryption',
        },
        {
          code: 'AC.L2-3.1.20',
          title: 'External Connections',
          description: 'Verify and control or limit connections to and use of external systems.',
          explanation: 'The organization must decide which external systems (partner portals, prime contractor exchanges, SaaS tools, home computers) may connect to or receive company data, and block the rest. The MSP maintains an approved external systems list in the SSP, enforces it with conditional access (block sign-in from unmanaged devices), DNS/web filtering to block unsanctioned SaaS, and policy prohibiting CUI on personal equipment. Assessors verify by reviewing the approved list, the enforcement mechanisms, and interviewing users about home computer use.',
          example: 'Compliant — Approved external systems list (prime contractor DIBNet portal, Exostar) documented in SSP appendix C; conditional access blocks M365 from unmanaged devices; unsanctioned file-sharing SaaS blocked at DNS filter; AUP prohibits CUI on personal devices, signed by all staff.',
          nist: 'AC-20',
          type: 'administrative',
        },
        {
          code: 'AC.L2-3.1.21',
          title: 'Portable Storage Use',
          description: 'Limit the use of organizational portable storage devices on external systems.',
          explanation: 'Company USB drives must not be plugged into uncontrolled computers — hotel kiosks, home PCs — where CUI could be copied or malware picked up. Most small contractors simplify by prohibiting portable storage for CUI entirely or issuing a small set of encrypted, serialized drives with usage rules. The MSP enforces this with removable storage restrictions via Intune/GPO (block or allow-list by device ID) and policy language in the AUP. Assessors verify by reviewing the device control policy and testing that an unauthorized USB drive is blocked.',
          example: 'Compliant — Removable storage blocked by Intune policy on all endpoints except two allow-listed FIPS-validated Apricorn drives assigned to engineering; test USB drive rejected on WKS-007 during the 2026-06-12 walkthrough; AUP prohibits use of company drives on non-company systems.',
          nist: 'AC-20(2)',
          type: 'technical',
        },
        {
          code: 'AC.L2-3.1.22',
          title: 'Public Information Control',
          description: 'Control information posted or processed on publicly accessible systems.',
          explanation: 'CUI must never end up on the public website, social media, or public file shares, so there needs to be a review step before content is published. For a small contractor this is a lightweight procedure: a designated reviewer approves website and marketing content, and the MSP verifies that public-facing systems (website, anonymous SharePoint links) cannot expose internal data. The MSP also disables anonymous sharing links in the M365 tenant or restricts them to non-CUI sites. Assessors verify by reviewing the publication procedure, the tenant sharing settings, and sampling recent public postings.',
          example: 'Compliant — Marketing content requires approval by the FSO per procedure PUB-01; anonymous sharing disabled tenant-wide in GCC High; quarterly review of the public website completed 2026-05-30 with no CUI findings.',
          nist: 'AC-22',
          type: 'administrative',
        },
      ],
    },
    {
      code: 'AT',
      title: 'Awareness and Training',
      description: 'Ensures all personnel understand the security risks of their activities and are trained to carry out their security-related duties.',
      controls: [
        {
          code: 'AT.L2-3.2.1',
          title: 'Role-Based Risk Awareness',
          description: 'Ensure that managers, system administrators, and users are made aware of the security risks associated with their activities and the applicable policies and procedures.',
          explanation: 'Everyone who touches company systems needs recurring security awareness training covering phishing, CUI handling, acceptable use, and how to report suspicious activity. MSPs typically deliver this through a managed platform such as Huntress Security Awareness Training or KnowBe4, with monthly or quarterly modules, simulated phishing, and automatic tracking of completion. New hires complete training before receiving CUI access, and completion records are retained as evidence. Assessors verify by reviewing the completion report, the training content, and interviewing a sample of users.',
          example: 'Compliant — Huntress SAT assigned to all 22 users with monthly modules; June 2026 completion report shows 22/22 complete; simulated phish click rate down from 14% to 3% over 12 months; new-hire training completed before account issuance per onboarding checklist.',
          nist: 'AT-2',
          type: 'administrative',
          auto: 'huntress',
          autoCheck: 'sat_completion',
        },
        {
          code: 'AT.L2-3.2.2',
          title: 'Role-Based Training',
          description: 'Ensure that personnel are trained to carry out their assigned information security related duties and responsibilities.',
          explanation: 'Beyond general awareness, people with specific security duties — the ISSO/FSO, IT admins, anyone who marks or handles CUI — need training matched to those duties. For a small contractor this typically means CUI marking and handling training for program staff, incident response role training for the designated responders, and documented technical training for the MSP technicians who administer the environment. Training assignments are mapped to roles in a simple matrix and completion is tracked. Assessors verify by reviewing the role-to-training matrix and sampling completion evidence for security-relevant roles.',
          example: 'Partial — IT admin and ISSO completed CUI handling and incident response training in Q1 2026; however, two newly assigned program managers who mark CUI have not yet completed marking training — assigned in Huntress SAT with a 2026-07-31 due date.',
          nist: 'AT-3',
          type: 'administrative',
          auto: 'huntress',
          autoCheck: 'sat_completion',
        },
        {
          code: 'AT.L2-3.2.3',
          title: 'Insider Threat Awareness',
          description: 'Provide security awareness training on recognizing and reporting potential indicators of insider threat.',
          explanation: 'Staff must be trained to spot and report insider threat indicators — unusual data hoarding, attempts to bypass controls, disgruntlement combined with access to sensitive programs — and know the reporting channel. MSPs cover this with a dedicated insider threat module in the awareness platform, delivered at hire and refreshed annually, plus a documented reporting path to the FSO or ISSO. The training should reference CUI and DoD program context, not just generic examples. Assessors verify by reviewing the module content, completion records, and asking sampled employees how they would report a concern.',
          example: 'Compliant — Annual insider threat module completed by 22/22 users in March 2026; module content covers data exfiltration and behavioral indicators; interviewed users correctly identified the FSO as the reporting channel.',
          nist: 'AT-2(2)',
          type: 'administrative',
        },
      ],
    },
    {
      code: 'AU',
      title: 'Audit and Accountability',
      description: 'Creates, protects, retains, and reviews audit logs so individual user actions can be traced, investigated, and reported.',
      controls: [
        {
          code: 'AU.L2-3.3.1',
          title: 'System Auditing',
          description: 'Create and retain system audit logs and records to enable monitoring, analysis, investigation, and reporting of unlawful or unauthorized system activity.',
          explanation: 'Systems handling CUI must generate security-relevant logs — logons, privilege use, object access, policy changes — and retain them long enough to support an investigation (commonly 90 days hot, one year archived). MSPs implement this with Windows advanced audit policy via GPO/Intune, M365 unified audit logging, firewall logging, and centralized collection into a managed SIEM or the Huntress SOC platform. Retention is documented in the SSP. Assessors verify by reviewing the audit policy, sampling collected events, and confirming retention against the stated period.',
          example: 'Compliant — Windows audit policy deployed via GPO; endpoint, server, M365, and FortiGate logs collected in the Huntress-managed SIEM with 12-month retention; sampled events from 2025-09 successfully retrieved during assessment.',
          nist: 'AU-2',
          type: 'technical',
          auto: 'huntress',
          autoCheck: 'siem_logging',
        },
        {
          code: 'AU.L2-3.3.2',
          title: 'User Accountability',
          description: 'Ensure that the actions of individual system users can be uniquely traced to those users so they can be held accountable.',
          explanation: 'Accountability requires unique accounts — no shared logons for shop floor PCs or generic admin accounts used by multiple people — so that every audit record maps to one human. The MSP enforces unique named accounts in AD/Entra ID, converts legacy shared accounts to individual ones or documents kiosk exceptions with compensating controls, and ensures service accounts are inventoried and not used interactively. Assessors verify by reviewing the account list for shared accounts and tracing sampled audit events back to individuals.',
          example: 'Partial — All office staff have unique accounts, but a shared "shipping" login remains on two warehouse PCs that can reach the ERP; POA&M item to issue individual badge-tap logons by 2026-08-31; interim compensating control restricts the shared account to the shipping application only.',
          nist: 'AU-3',
          type: 'technical',
        },
        {
          code: 'AU.L2-3.3.4',
          title: 'Audit Failure Alerting',
          description: 'Alert in the event of an audit logging process failure.',
          explanation: 'If logging silently stops — an agent dies, a disk fills, a log source goes quiet — someone must be alerted promptly, because attackers often disable logging first. MSPs implement this with SIEM log-source health monitoring that alerts when a host stops reporting, RMM checks on logging services and disk space, and alerting on Windows event 1104/1102 (log full or cleared). Alerts route to the MSP service desk with a defined response time. Assessors verify by reviewing the alerting configuration and evidence of a past alert being generated and worked.',
          example: 'Compliant — SIEM alerts when any log source is silent for 4 hours; RMM monitors the event log service and disk thresholds on all servers; ticket #4788 from 2026-04-02 shows a stopped forwarder alerted and remediated within 3 hours.',
          nist: 'AU-5',
          type: 'technical',
        },
        {
          code: 'AU.L2-3.3.5',
          title: 'Audit Correlation',
          description: 'Correlate audit record review, analysis, and reporting processes for investigation and response to indications of suspicious activity.',
          explanation: 'Logs from different sources must be analyzed together — an odd VPN logon plus an unusual file access is far more meaningful than either alone. Small contractors almost never staff this themselves; the MSP provides it through a managed SOC (Huntress) that correlates endpoint, identity, and M365 signals 24x7 and escalates verified incidents. Correlation findings feed the incident response process. Assessors verify by reviewing the SOC service description, sample escalations, and how a recent alert was investigated across sources.',
          example: 'Compliant — Huntress managed SOC correlates EDR, M365, and identity telemetry 24x7; escalation from 2026-05-19 (impossible-travel logon correlated with inbox rule creation) documented in ticket #4903 with containment within 40 minutes.',
          nist: 'AU-6',
          type: 'technical',
          auto: 'huntress',
          autoCheck: 'soc_monitoring',
        },
        {
          code: 'AU.L2-3.3.6',
          title: 'Reduction & Reporting',
          description: 'Provide audit record reduction and report generation to support on-demand analysis and reporting.',
          explanation: 'Raw logs are useless in bulk; the organization needs tooling that can filter, search, and summarize audit data on demand — for an investigation, a spot check, or an assessor request. The MSP satisfies this with the SIEM search and dashboard capability, M365 Purview audit search, and scheduled monthly security summary reports delivered to the client. The key test is being able to answer a question like "show all logons for user X in March" quickly. Assessors verify by requesting a live query and reviewing sample reports.',
          example: 'Compliant — SIEM provides ad hoc search and saved dashboards; monthly security report delivered to the ISSO (May 2026 copy reviewed); live query for a named user across 90 days of logons returned during the assessment in under two minutes.',
          nist: 'AU-7',
          type: 'technical',
        },
        {
          code: 'AU.L2-3.3.7',
          title: 'Authoritative Time Source',
          description: 'Provide a system capability that compares and synchronizes internal system clocks with an authoritative source to generate accurate time stamps for audit records.',
          explanation: 'Audit records are only correlatable if all systems agree on the time, so every server, workstation, and network device must sync to an authoritative NTP source. The MSP configures the domain controller to sync with a reliable external source (e.g. time.nist.gov or pool NTP), domain members to sync via the Windows time hierarchy, and network gear to the same source, with RMM checks flagging clock drift. Assessors verify by reviewing the NTP configuration and comparing timestamps across sampled systems.',
          example: 'Compliant — PDC emulator syncs to time.nist.gov; domain members follow the domain hierarchy; FortiGate and Meraki configured to the same source; RMM clock-drift check shows all 38 monitored systems within 2 seconds as of 2026-06-30.',
          nist: 'AU-8',
          type: 'technical',
          auto: 'ncentral',
          autoCheck: 'ntp_sync',
        },
        {
          code: 'AU.L2-3.3.8',
          title: 'Audit Protection',
          description: 'Protect audit information and audit logging tools from unauthorized access, modification, and deletion.',
          explanation: 'Attackers and malicious insiders try to erase their tracks, so logs and the logging pipeline must be tamper-resistant. MSPs achieve this by forwarding logs off-host to the SIEM in near real time (so clearing a local log does not destroy evidence), restricting SIEM access to MSP security staff and the client ISSO, and alerting on event 1102 (audit log cleared). Local log files and agents are protected by ACLs and EDR tamper protection. Assessors verify by reviewing SIEM access permissions, forwarding latency, and the log-cleared alerting rule.',
          example: 'Compliant — Logs forwarded to the managed SIEM within minutes of generation; SIEM access limited to 3 MSP security staff and the client ISSO (read-only); event 1102 generates a priority alert; Huntress tamper protection prevents agent shutdown by local admins.',
          nist: 'AU-9',
          type: 'technical',
        },
        {
          code: 'AU.L2-3.3.9',
          title: 'Audit Management',
          description: 'Limit management of audit logging functionality to a subset of privileged users.',
          explanation: 'Only a small, named group may change what gets logged, adjust retention, or administer the SIEM — regular admins should not be able to quietly reduce audit coverage. The MSP documents who holds audit-management rights (typically two or three MSP security engineers), enforces it through SIEM role-based access and GPO change control on audit policy, and logs changes to the logging configuration itself. Assessors verify by enumerating SIEM admin roles and reviewing who can modify the audit GPOs.',
          example: 'Compliant — SIEM administration limited to 2 named MSP security engineers; audit policy GPO changes restricted by AD delegation and captured in the change log; client-side users have read-only report access.',
          nist: 'AU-9(4)',
          type: 'administrative',
        },
      ],
    },
    {
      code: 'CM',
      title: 'Configuration Management',
      description: 'Establishes and maintains secure baseline configurations and controls how changes to systems are proposed, approved, and tracked.',
      controls: [
        {
          code: 'CM.L2-3.4.1',
          title: 'System Baselining',
          description: 'Establish and maintain baseline configurations and inventories of organizational systems throughout their life cycles.',
          explanation: 'The organization needs a documented picture of what a correctly configured system looks like (OS version, installed software, security settings) and a current inventory of everything in scope. The MSP maintains the asset inventory automatically through the RMM agent, builds standard workstation and server images or Intune configuration profiles as the baseline, and reviews the inventory for unknown devices. Baseline documents live with the SSP and are updated when the standard changes. Assessors verify by comparing the inventory to systems observed on-site and reviewing the baseline documentation for currency.',
          example: 'Compliant — RMM inventory covers 38 endpoints/servers reconciled quarterly against purchasing records; baseline defined by Intune configuration profiles and the WS-2024 standard image document (last updated 2026-03); no unknown devices in the June network scan.',
          nist: 'CM-2',
          type: 'administrative',
        },
        {
          code: 'CM.L2-3.4.2',
          title: 'Security Configuration Enforcement',
          description: 'Establish and enforce security configuration settings for information technology products employed in organizational systems.',
          explanation: 'Security settings — patch levels, firewall state, SMB signing, disabled legacy protocols — must be defined and technically enforced, not left to per-machine chance. MSPs deploy hardened settings through GPO and Intune (often aligned to CIS or DISA STIG benchmarks where practical), keep systems current through automated RMM patching, and use RMM policy checks to detect drift. Non-compliant machines surface on a dashboard and get remediated on a schedule. Assessors verify by reviewing the configuration standard, sampling effective settings on endpoints, and reviewing patch compliance reports.',
          example: 'Compliant — CIS-aligned Intune security baseline applied to all endpoints; N-central patch policy shows 97% of systems fully patched within 14 days of release (June 2026 report); SMBv1 and LLMNR confirmed disabled on sampled hosts.',
          nist: 'CM-6',
          type: 'technical',
          auto: 'ncentral',
          autoCheck: 'patch_compliance',
        },
        {
          code: 'CM.L2-3.4.3',
          title: 'System Change Management',
          description: 'Track, review, approve or disapprove, and log changes to organizational systems.',
          explanation: 'Changes to servers, firewalls, and security tooling must go through a lightweight but real change process — a ticket describing the change, an approval, and a record of what was done. For MSP-managed environments this lives in the PSA ticketing system: significant changes get a change ticket with client approval (often the ISSO) before work, and emergency changes are documented after the fact. Routine patching runs under a standing pre-approved change. Assessors verify by sampling recent changes (a firewall rule, a new server) and tracing each to an approved ticket.',
          example: 'Partial — Firewall and server changes tracked in PSA change tickets with ISSO approval (samples #4821, #4867 verified); however, a DNS filter policy change on 2026-05-14 was made without a ticket — process reinforced with technicians and retroactive record created.',
          nist: 'CM-3',
          type: 'administrative',
        },
        {
          code: 'CM.L2-3.4.4',
          title: 'Security Impact Analysis',
          description: 'Analyze the security impact of changes prior to implementation.',
          explanation: 'Before a change is made, someone must ask what it does to the security posture — does opening this port expose CUI, does this new SaaS tool create a new data flow? In practice the MSP adds a short security-impact field to the change ticket template, and changes touching boundary devices, authentication, or CUI systems get reviewed by a senior engineer before approval. The analysis can be brief but must exist and be recorded. Assessors verify by sampling change tickets for completed impact analysis, especially on firewall and identity changes.',
          example: 'Compliant — Change template includes a mandatory security impact section; sampled tickets #4821 (VPN cipher update) and #4903 (new SFTP flow to prime contractor) show documented impact analysis and senior engineer review before approval.',
          nist: 'CM-4',
          type: 'administrative',
        },
        {
          code: 'CM.L2-3.4.5',
          title: 'Access Restrictions for Change',
          description: 'Define, document, approve, and enforce physical and logical access restrictions associated with changes to organizational systems.',
          explanation: 'Only authorized people may actually implement changes — which means restricting who holds admin credentials to servers, firewalls, Intune, and the RMM itself. The MSP documents which roles can change what, enforces it with role-based access in each management plane (RMM technician roles, firewall admin accounts, Entra ID privileged roles), and protects those credentials with MFA. Physical access to server hardware follows the PE controls. Assessors verify by enumerating who holds change-capable access in each system and matching it to the documented authorization.',
          example: 'Compliant — Change-capable access documented in SSP appendix D: 4 MSP engineers (RMM/Intune/firewall) and 1 client IT admin (limited to workstation support); all management-plane accounts enforce Duo or Entra MFA; access list reviewed 2026-06-20.',
          nist: 'CM-5',
          type: 'administrative',
        },
        {
          code: 'CM.L2-3.4.6',
          title: 'Least Functionality',
          description: 'Employ the principle of least functionality by configuring organizational systems to provide only essential capabilities.',
          explanation: 'Systems should run only what their mission requires — unnecessary services, roles, and listening ports are attack surface. The MSP hardens standard images and server builds by disabling unneeded Windows features and services, removes bloatware from workstations, and uses continuous internal scanning (Nodeware) to detect unexpected open ports. Findings are triaged and either justified in documentation or closed. Assessors verify by reviewing recent scan results and asking for the justification of unusual open services.',
          example: 'Compliant — Nodeware internal scan 2026-06-25 shows no unexpected listening services; print spooler disabled on all servers except PRINT01; deviation for port 8443 on the ERP server documented and vendor-required.',
          nist: 'CM-7',
          type: 'technical',
          severity: 'high',
          auto: 'nodeware',
          autoCheck: 'open_ports',
        },
        {
          code: 'CM.L2-3.4.7',
          title: 'Nonessential Functionality',
          description: 'Restrict, disable, or prevent the use of nonessential programs, functions, ports, protocols, and services.',
          explanation: 'This extends least functionality into active prevention: legacy and risky protocols (SMBv1, Telnet, FTP), unneeded applications, and unused ports must be explicitly disabled or blocked, not merely unused. The MSP disables legacy protocols via GPO/Intune, blocks nonessential outbound ports at the firewall, and removes or blocks software with no business purpose. A short documented list records which functions were disabled and why. Assessors verify by testing for legacy protocols on sampled systems and reviewing firewall egress rules.',
          example: 'Compliant — SMBv1, Telnet, and TLS 1.0/1.1 disabled via configuration baseline (verified on 3 sampled hosts); firewall egress limited to approved ports with deny-all default; nonessential-services register maintained in the SSP.',
          nist: 'CM-7(1)',
          type: 'technical',
        },
        {
          code: 'CM.L2-3.4.8',
          title: 'Application Execution Policy',
          description: 'Apply deny-by-exception (blacklisting) policy to prevent the use of unauthorized software, or deny-all permit-by-exception (whitelisting) policy to allow execution of authorized software.',
          explanation: 'The organization must control which software can execute — at minimum a deny-list of prohibited software, and ideally allow-listing on CUI systems. MSPs commonly implement this with EDR-based application controls or Windows Defender Application Control/AppLocker in audit-then-enforce mode, plus RMM software inventory alerts when unapproved applications appear. Remote-access tools, torrent clients, and unauthorized cloud sync agents are typical deny-list entries. Assessors verify by reviewing the policy configuration, the blocked-software list, and evidence of an actual block or alert.',
          example: 'Partial — Deny-list enforced via Huntress and RMM software inventory alerts (AnyDesk block on 2026-05-22 verified); AppLocker allow-listing piloted on the two CAD workstations but not yet enforced across all CUI endpoints — POA&M target 2026-09-30.',
          nist: 'CM-7(4)',
          type: 'technical',
        },
        {
          code: 'CM.L2-3.4.9',
          title: 'User-Installed Software',
          description: 'Control and monitor user-installed software.',
          explanation: 'Users must not be able to install arbitrary software, and anything that does get installed must be visible to IT. Removing local admin rights (see AC.L2-3.1.5) prevents most installs; the MSP then provides an approved-software request path through the service desk and monitors the RMM software inventory for new or unexpected titles. Monthly inventory diffs catch anything that slipped through. Assessors verify by attempting an install as a standard user, reviewing the request procedure, and sampling inventory reports.',
          example: 'Compliant — Standard users cannot install software (test install blocked on WKS-014); software requests flow through the MSP service desk with 14 approvals YTD; RMM new-software report reviewed monthly, June report shows no unauthorized titles.',
          nist: 'CM-11',
          type: 'technical',
        },
      ],
    },
    // __MORE_AREAS__
  ],
};
