// PCI-DSS 4.0 framework content — IT-managed scope for MSPs supporting small merchants.
// Dropped from the source requirement list: 12.4 (compliance program management is a
// merchant executive responsibility) and 12.9 (service provider acknowledgements are
// issued by service providers, not managed for the merchant by the MSP).

import type { FrameworkData } from './types.js';

export const PCI_FRAMEWORK: FrameworkData = {
  key: 'pci',
  name: 'PCI-DSS',
  shortName: 'PCI-DSS',
  version: '4.0',
  description: 'Payment Card Industry Data Security Standard v4.0 — requirements for protecting cardholder data environments.',
  nistMappingEnabled: false,
  contentVersion: 2,
  metadata: { publisher: 'PCI Security Standards Council', effectiveDate: '2024-03-31' },
  areas: [
    {
      code: 'REQ-1',
      title: 'Install and Maintain Network Security Controls',
      description: 'Deploy and manage firewalls and other network security controls that isolate the cardholder data environment from untrusted networks.',
      controls: [
        {
          code: '1.1',
          title: 'Network Security Policies',
          description: 'Define and document processes and mechanisms for installing and maintaining network security controls.',
          explanation: 'PCI-DSS 4.0 requires written, current procedures that describe how firewalls and other network security controls are configured, changed, and reviewed. For a small merchant this is a short document covering who manages the firewall, how rule changes are requested and approved, and how often the ruleset is reviewed. The MSP typically owns this document as part of its managed firewall service and keeps it in the client documentation system. Assessors expect the procedures to match what is actually deployed, so the MSP should update the document whenever the network changes.',
          example: 'Compliant — Managed firewall runbook for the client stored in IT Glue, last revised 2026-04-12; covers Fortigate change control, semiannual rule review, and named responsible engineer. Procedures match the deployed configuration.',
          type: 'administrative',
        },
        {
          code: '1.2',
          title: 'Network Security Controls (NSCs)',
          description: 'Configure and maintain network security controls that restrict traffic into and out of the cardholder data environment.',
          explanation: 'This requires an actual firewall or equivalent control at every boundary of the CDE, configured with a deny-by-default ruleset and kept current. For a small merchant the MSP deploys a business-class firewall (Fortigate, SonicWall, Meraki), documents the ruleset, and reviews rules at least every six months as 4.0 requires. Configuration backups and firmware updates are handled through the MSP firewall management platform. Network scanning tools can confirm a firewall is present and that no unmanaged edge devices exist.',
          example: 'Compliant — Fortigate 60F at the office edge, firmware 7.4.4, deny-all default policy; ruleset export reviewed 2026-06-08 and archived; config backed up nightly to FortiManager.',
          type: 'technical',
          severity: 'critical',
          auto: 'nodeware',
          autoCheck: 'firewall_present',
        },
        {
          code: '1.3',
          title: 'Network Access Restriction',
          description: 'Restrict all network access to and from the cardholder data environment to only what is necessary.',
          explanation: 'Traffic into the CDE must be limited to authorized systems and ports, and outbound traffic from the CDE must be explicitly permitted rather than open. In practice the MSP segments the CDE onto its own VLAN or dedicated network, with firewall policies that allow only POS-to-processor traffic and required management access. Guest Wi-Fi, office workstations, and IoT devices must not be able to reach payment systems. The MSP verifies segmentation with firewall policy review and periodic scans from outside the segment.',
          example: 'Compliant — CDE segmented on VLAN 40 behind the Fortigate; only POS terminals and the payment server present; inter-VLAN policy allows outbound TLS to the processor only; segmentation checked via Nodeware scan from the office VLAN 2026-05-20 with no CDE hosts reachable.',
          type: 'technical',
          severity: 'critical',
        },
        {
          code: '1.4',
          title: 'Trusted/Untrusted Boundaries',
          description: 'Control all network connections between trusted internal networks and untrusted networks such as the internet.',
          explanation: 'Every link between the internal network and an untrusted network must pass through a network security control, and inbound traffic from the internet must terminate in a controlled zone rather than directly inside the CDE. Anti-spoofing measures and blocking of unauthorized outbound traffic are also expected. The MSP implements this with edge firewall policies, a DMZ for any public-facing services, and NAT so internal addressing is not exposed. For most small merchants there are no inbound services at all, which the MSP confirms with an external scan.',
          example: 'Compliant — Single internet handoff through the managed Fortigate; no inbound NAT rules; external ASV scan by SecurityMetrics 2026-05-14 shows no open inbound ports; anti-spoofing enabled on the WAN interface.',
          type: 'technical',
          severity: 'high',
        },
        {
          code: '1.5',
          title: 'Risk Mitigation',
          description: 'Mitigate risks to the CDE from computing devices that connect to both untrusted networks and the CDE.',
          explanation: 'Laptops and other devices that leave the office and later touch the CDE need host-level protections, since they can carry threats past the perimeter firewall. PCI-DSS 4.0 expects personal firewall or equivalent controls on such devices, configured so users cannot disable them. The MSP typically enforces the Windows firewall profile and EDR via RMM policy on any technician or back-office laptop that can reach payment systems. Where possible the cleaner answer is to block roaming devices from the CDE VLAN entirely.',
          example: 'Partial — Back-office laptop LT-ACCT01 can reach the payment server VLAN; Windows firewall enforced via N-central policy and Huntress EDR installed, but the user retains local admin and could alter firewall settings. Remediation ticket #48122 opened to remove local admin.',
          type: 'technical',
        },
      ],
    },
    {
      code: 'REQ-2',
      title: 'Apply Secure Configuration Standards',
      description: 'Harden all system components and wireless environments by removing defaults and applying documented secure configuration baselines.',
      controls: [
        {
          code: '2.1',
          title: 'Secure Configuration Policies',
          description: 'Define and document processes for applying secure configurations to all system components.',
          explanation: 'The standard requires documented configuration procedures so hardening is repeatable rather than ad hoc. For a small merchant this means the MSP maintains build checklists or baseline documents for firewalls, servers, workstations, and POS-adjacent systems. The documents should state that vendor defaults are removed, unnecessary services are disabled, and who is responsible for applying the baseline. MSPs usually satisfy this with standard onboarding checklists and RMM policy templates stored in the documentation platform.',
          example: 'Compliant — Workstation and server build checklists v3.2 in IT Glue dated 2026-02; includes default account removal, service hardening, and CIS-aligned settings; applied via N-central onboarding policy.',
          type: 'administrative',
        },
        {
          code: '2.2',
          title: 'System Configuration Standards',
          description: 'Configure and manage all system components securely, including removing vendor defaults and unnecessary functionality.',
          explanation: 'All systems in or connected to the CDE must be hardened: default passwords changed, unneeded services and accounts removed, insecure protocols disabled, and one primary function per server where feasible. The MSP enforces this through RMM configuration policies, patch management, and periodic configuration audits. Vulnerability scans catch drift such as re-enabled SMBv1 or default SNMP strings. Patch compliance reporting from the RMM is a practical ongoing indicator that systems are being maintained to the baseline.',
          example: 'Compliant — All 14 in-scope endpoints on N-central patch policy at 97 percent compliance as of 2026-06-30; default admin accounts renamed and disabled; SMBv1 and Telnet disabled by policy; last configuration audit 2026-04.',
          type: 'technical',
          severity: 'high',
          auto: 'ncentral',
          autoCheck: 'patch_compliance',
        },
        {
          code: '2.3',
          title: 'Wireless Security',
          description: 'Configure and manage all wireless environments securely, changing wireless vendor defaults and using strong encryption.',
          explanation: 'Any wireless network connected to the CDE, or that could reach it, must have default SSIDs, passwords, and SNMP settings changed, and must use current strong encryption such as WPA2-Enterprise or WPA3. Wireless keys must be changed when staff with knowledge of them leave. The MSP manages this through the wireless controller (UniFi, Meraki, Aruba), keeps guest Wi-Fi fully isolated from the CDE, and documents the wireless configuration. If no wireless touches the CDE, the MSP documents that isolation as the control.',
          example: 'Compliant — UniFi wireless managed by MSP; corporate SSID on WPA3, guest SSID isolated on VLAN 90 with client isolation; no wireless bridged to CDE VLAN 40; PSK rotated 2026-03 after a staff departure.',
          type: 'technical',
        },
      ],
    },
    {
      code: 'REQ-3',
      title: 'Protect Stored Account Data',
      description: 'Minimize storage of cardholder data and protect any stored account data with encryption, masking, and sound key management.',
      controls: [
        {
          code: '3.1',
          title: 'Data Retention Policies',
          description: 'Define and document processes and mechanisms for protecting stored account data.',
          explanation: 'The merchant needs documented rules covering what account data may be stored, for how long, and how it is protected and destroyed. For most small merchants the correct policy is that no cardholder data is stored at all outside the validated payment application. The MSP helps draft and maintain this policy and implements the technical side, such as quarterly scans for stray card data on file shares and workstations. The policy should name a retention period and a secure deletion method for anything legitimately retained.',
          example: 'Compliant — Data retention policy in the client compliance binder, updated 2026-01, states no PAN storage outside the P2PE terminal; quarterly PII/PAN discovery scan of the file server ran 2026-06-02 with zero findings.',
          type: 'administrative',
        },
        {
          code: '3.2',
          title: 'Sensitive Authentication Data',
          description: 'Keep storage of account data to the minimum required for business and legal needs.',
          explanation: 'PCI-DSS 4.0 requires that account data storage be minimized through defined retention periods and periodic purging, with anything beyond the defined need securely deleted. For a small merchant the MSP verifies that the POS and back-office systems are not accumulating card numbers in exports, reports, email, or scanned documents. Data discovery scans run from the RMM or a dedicated tool provide evidence that storage really is minimal. Findings are purged and the source process is corrected so the data does not reappear.',
          example: 'Non-compliant — Discovery scan 2026-06-10 found a 2023 spreadsheet on the office share containing 41 full PANs from manual phone orders; file securely deleted 2026-06-11, staff retrained to use the terminal for phone orders, rescan scheduled for 2026-07.',
          type: 'administrative',
          severity: 'critical',
        },
        {
          code: '3.3',
          title: 'SAD Not Stored After Authorization',
          description: 'Ensure sensitive authentication data such as track data, CVV, and PINs is never stored after authorization.',
          explanation: 'Full magnetic stripe contents, card verification codes, and PIN data must never be retained once a transaction is authorized, even if encrypted. Modern validated POS and P2PE terminals handle this by design, so the MSP role for a small merchant is verifying the payment solution is a current, validated version and that nothing outside it captures card data. That includes confirming call recordings, order forms, and email are not collecting CVV values. Data discovery scans and a review of manual order-taking processes provide the evidence.',
          example: 'Compliant — Payments processed only through Verifone P400 P2PE terminals (validated solution, confirmed on the PCI SSC listing 2026-05); no card data entry into any workstation; discovery scan found no track or CVV data.',
          type: 'technical',
          severity: 'critical',
        },
        {
          code: '3.4',
          title: 'PAN Access Restriction',
          description: 'Mask displayed PANs and restrict the ability to view or copy full card numbers to personnel with a business need.',
          explanation: 'Screens and receipts must show at most the first six and last four digits of a card number unless a specific role needs more, and copying or relocating PAN via remote access must be technically restricted. For a small merchant this mostly means confirming the POS masks card numbers on screens and receipts, which validated applications do by default. The MSP also ensures remote access tools used for support cannot be used to export data from payment systems, for example by restricting clipboard and file transfer in the remote support tool for CDE hosts.',
          example: 'Compliant — POS receipts and back-office screens show last four only, verified on-site 2026-04-22; ScreenConnect session policy for the payment server disables file transfer and clipboard sync.',
          type: 'technical',
          severity: 'high',
        },
        {
          code: '3.5',
          title: 'PAN Secured Wherever Stored',
          description: 'Render PAN unreadable anywhere it is stored using strong cryptography, truncation, tokenization, or hashing.',
          explanation: 'If full card numbers are stored at all, they must be made unreadable with approved methods such as strong encryption or tokenization; disk-level encryption alone is no longer sufficient on its own under 4.0. For most MSP-supported merchants the right outcome is that no PAN is stored, with the processor handling tokenization. Where a payment application does store PAN, the MSP verifies the vendor documentation confirms field-level encryption and keeps that attestation on file. Disk encryption via BitLocker is still deployed on CDE systems as defense in depth.',
          example: 'Compliant — No local PAN storage; recurring billing uses processor tokens via the gateway vault; payment server has BitLocker enabled as defense in depth; vendor PA attestation for the POS software on file, dated 2025-11.',
          type: 'technical',
          severity: 'critical',
        },
        {
          code: '3.6',
          title: 'Cryptographic Key Management',
          description: 'Protect the cryptographic keys used to secure stored account data against disclosure and misuse.',
          explanation: 'Any keys that protect stored account data must be stored securely, restricted to the fewest custodians possible, and managed through documented procedures. In small merchant environments with P2PE terminals, key management is handled by the terminal vendor and processor, which drastically simplifies this requirement. The MSP documents that key custody sits with the payment vendor and manages the keys it does control, such as BitLocker recovery keys and any certificate private keys on the payment server, storing them in the MSP password vault with restricted access.',
          example: 'Compliant — Payment encryption keys managed by the P2PE solution provider per vendor attestation; BitLocker recovery keys escrowed in Keeper with access limited to two senior engineers; no other account-data keys exist in the environment.',
          type: 'technical',
          severity: 'critical',
        },
      ],
    },
    {
      code: 'REQ-4',
      title: 'Protect Cardholder Data in Transit',
      description: 'Encrypt cardholder data with strong cryptography whenever it is transmitted over open or public networks.',
      controls: [
        {
          code: '4.1',
          title: 'Transmission Security Policies',
          description: 'Define and document processes for protecting cardholder data with strong cryptography during transmission.',
          explanation: 'The merchant needs documented procedures describing how card data in transit is protected, what protocols and cipher strengths are acceptable, and who maintains the configuration. For a small merchant the MSP maintains a short standard: TLS 1.2 or higher for all payment traffic, no card data over email, chat, or fax, and an inventory of where card data flows. The data-flow diagram maintained under scoping work doubles as evidence here. The MSP reviews the document when payment systems change.',
          example: 'Compliant — Transmission security standard in the compliance binder, revised 2026-02; payment data-flow diagram shows terminal-to-processor TLS 1.3 only; policy prohibits card numbers via email and staff acknowledged it during 2026 training.',
          type: 'administrative',
        },
        {
          code: '4.2',
          title: 'Strong Cryptography in Transit',
          description: 'Protect PAN with strong cryptography whenever it is transmitted over open or public networks.',
          explanation: 'Card numbers crossing the internet, wireless networks, or cellular links must be encrypted with current strong protocols, with only trusted certificates accepted and an inventory of trusted keys and certificates maintained. P2PE terminals encrypt at the point of swipe or dip, so the data is already unreadable before it leaves the device. The MSP verifies terminal firmware is current, confirms TLS versions on any gateway connections, and uses ASV scan results to prove weak protocols like TLS 1.0 are not accepted anywhere in scope. Wireless carrying payment traffic must use WPA2 or better.',
          example: 'Compliant — P2PE terminals encrypt at capture; gateway connection enforces TLS 1.2+; SecurityMetrics ASV scan 2026-05-14 passed with no weak-cipher findings; certificate inventory maintained in IT Glue, next expiry 2027-01.',
          type: 'technical',
          severity: 'critical',
        },
      ],
    },
    {
      code: 'REQ-5',
      title: 'Protect from Malicious Software',
      description: 'Deploy and maintain anti-malware and anti-phishing protections across all systems that could affect the cardholder data environment.',
      controls: [
        {
          code: '5.1',
          title: 'Anti-Malware Policies',
          description: 'Define and document processes for protecting all systems and networks from malicious software.',
          explanation: 'The standard requires written procedures describing how malware protection is deployed, kept current, and monitored. For an MSP-managed merchant this is largely the managed security service description: which EDR product is deployed, how alerts are triaged, and how coverage gaps are detected. The document should also address systems considered not at risk from malware, which must be periodically re-evaluated under 4.0. Most MSPs satisfy this with their standard security stack documentation attached to the client record.',
          example: 'Compliant — Managed EDR service description on file listing Huntress on all Windows endpoints, 24x7 SOC triage, and quarterly coverage reconciliation against the RMM asset list; last reviewed 2026-03.',
          type: 'administrative',
        },
        {
          code: '5.2',
          title: 'Anti-Malware Deployed',
          description: 'Deploy anti-malware protection on all in-scope systems so malicious software is prevented or detected and addressed.',
          explanation: 'Every system component at risk from malware must run an anti-malware solution capable of detecting, blocking, and addressing current threats. The MSP deploys EDR such as Huntress plus Defender across all workstations and servers, including the payment server and any back-office machine that touches the CDE. Deployment is automated through the RMM so new machines are covered at onboarding. Coverage is verified by reconciling the EDR console against the RMM asset inventory rather than assuming the agent installed everywhere.',
          example: 'Compliant — Huntress plus Microsoft Defender active on 14 of 14 in-scope endpoints; console-to-RMM reconciliation 2026-06-27 showed no gaps; POS terminals are vendor-locked P2PE devices documented as out of agent scope.',
          type: 'technical',
          severity: 'high',
          auto: 'huntress',
          autoCheck: 'edr_active',
        },
        {
          code: '5.3',
          title: 'Anti-Malware Active and Maintained',
          description: 'Keep anti-malware mechanisms current, actively running, monitored, and protected from being disabled by users.',
          explanation: 'It is not enough to install the agent; definitions and engines must update automatically, periodic and real-time scanning must run, logs must be retained, and users must not be able to disable protection without management authorization. The MSP enforces this with tamper protection on the EDR, RMM monitoring that alerts when an agent goes stale or offline, and SOC review of detections. Audit evidence is the EDR console health report showing agents current and protected.',
          example: 'Partial — All agents current, but tamper protection was found disabled on the payment server after a vendor support session on 2026-06-15; re-enabled same day and a change-control note added requiring MSP approval for vendor sessions on CDE hosts.',
          type: 'technical',
          auto: 'huntress',
          autoCheck: 'edr_active',
        },
        {
          code: '5.4',
          title: 'Anti-Phishing Mechanisms',
          description: 'Implement processes and automated mechanisms that protect users against phishing attacks.',
          explanation: 'New in 4.0, this requires technical anti-phishing controls, not just training: email filtering, link and attachment protection, and domain anti-spoofing such as SPF, DKIM, and DMARC. The MSP typically configures Microsoft 365 Defender or a third-party email security layer, publishes DMARC for the merchant domain, and runs ongoing phishing simulation and awareness training. Security awareness completion reporting complements the technical controls as evidence that users are being tested against realistic lures.',
          example: 'Compliant — M365 Defender Safe Links and Safe Attachments enabled; SPF, DKIM, and DMARC (p=quarantine) published for the merchant domain; Huntress SAT phishing simulations monthly with 92 percent completion for Q2 2026.',
          type: 'technical',
          auto: 'huntress',
          autoCheck: 'sat_completion',
        },
      ],
    },
    {
      code: 'REQ-6',
      title: 'Develop and Maintain Secure Systems',
      description: 'Keep systems and software secure through vulnerability management, timely patching, controlled changes, and protection of any web-facing applications.',
      controls: [
        {
          code: '6.1',
          title: 'Secure Development Policies',
          description: 'Define and document processes for developing and maintaining secure systems and software.',
          explanation: 'This requires documented procedures for how software in the environment is kept secure over its lifecycle. Small merchants rarely develop software, so the practical content is how commercial software is selected, updated, and retired, and how the POS vendor relationship is managed. The MSP documents its patching standards, supported-software policy, and the process for tracking vendor security bulletins for the payment application. If the merchant truly has no custom software, the policy states that and covers maintenance of purchased systems.',
          example: 'Compliant — No custom software in the environment; secure maintenance policy dated 2026-01 covers MSP patching SLAs, POS vendor bulletin monitoring, and removal of end-of-life software; Windows 10 endpoints retired ahead of EOL per plan.',
          type: 'administrative',
        },
        {
          code: '6.2',
          title: 'Bespoke/Custom Software Security',
          description: 'Ensure any bespoke or custom software is developed securely and reviewed for vulnerabilities before release.',
          explanation: 'Where custom code exists — including website customizations, integrations, or scripts that touch payment flows — it must be developed with secure coding practices, code review, and developer training. For most small merchants the only candidate is their e-commerce site; if payments are fully redirected to a hosted payment page, the custom code is out of the direct CDE but the redirect itself must be protected. The MSP inventories any custom components, confirms who maintains them, and ensures the web developer follows a review process for changes that could affect the payment redirect.',
          example: 'Compliant — Only custom component is the WordPress site with a hosted-checkout redirect to the processor; changes deployed via staging with agency peer review; MSP confirms redirect integrity after each release, last check 2026-06-03.',
          type: 'technical',
        },
        {
          code: '6.3',
          title: 'Security Vulnerabilities Identified',
          description: 'Identify, risk-rank, and remediate security vulnerabilities across all system components.',
          explanation: 'The merchant must have an ongoing process to learn about new vulnerabilities, rank them by risk, and patch critical issues within one month of release. The MSP implements this with continuous vulnerability scanning (Nodeware or similar), RMM-driven patch management for Windows and third-party applications, and monitoring of vendor advisories for the firewall and POS stack. A complete software inventory underpins the process, since unknown software cannot be patched. Scan reports and patch compliance dashboards are the standing evidence.',
          example: 'Compliant — Nodeware continuous scanning across VLANs 10 and 40; June 2026 report shows zero critical and two medium findings, both remediated within 14 days; N-central patches OS and third-party apps weekly with critical patches expedited.',
          type: 'technical',
          severity: 'high',
          auto: 'nodeware',
          autoCheck: 'vuln_scan',
        },
        {
          code: '6.4',
          title: 'Public-Facing Web Security',
          description: 'Protect public-facing web applications against known attacks with reviews or an automated technical solution.',
          explanation: 'Any public-facing web application in scope must be protected either through regular vulnerability assessments or an automated solution such as a web application firewall that blocks attacks in real time. New in 4.0, payment page scripts must also be inventoried, authorized, and integrity-checked. For a small merchant with a hosted e-commerce checkout, the MSP places the site behind a WAF such as Cloudflare, ensures the platform is patched, and works with the processor on script integrity for the checkout flow. If there is no public web application taking payments, the MSP documents that scope determination.',
          example: 'Compliant — Storefront behind Cloudflare WAF with managed OWASP ruleset; checkout is a hosted payment page (processor manages payment scripts); platform plugins auto-updated with monthly review, last review 2026-06-20.',
          type: 'technical',
        },
        {
          code: '6.5',
          title: 'Change Management',
          description: 'Manage all changes to system components securely through a documented change control process.',
          explanation: 'Changes to systems in the CDE must follow a process that records the reason for the change, approval, security impact review, testing, and a back-out plan. For an MSP-supported small merchant, the MSP ticketing system is the change record: firewall rule changes, payment server patches, and POS updates each get a ticket with approval and rollback notes. Significant changes also trigger a check that PCI controls still apply, such as confirming segmentation after network changes. Production and any test environments must be kept separate.',
          example: 'Compliant — All CDE changes tracked in the PSA; sampled tickets #47201 (firewall rule add) and #47554 (payment server patching) show approval, impact note, and rollback plan; segmentation re-verified after the 2026-04 switch replacement.',
          type: 'administrative',
        },
      ],
    },
    {
      code: 'REQ-7',
      title: 'Restrict Access to System Components',
      description: 'Limit access to systems and cardholder data to only those individuals whose job requires it, enforced by an access control system.',
      controls: [
        {
          code: '7.1',
          title: 'Access Control Policies',
          description: 'Define and document processes for restricting access to system components and cardholder data by business need to know.',
          explanation: 'The merchant needs a written access control model describing roles, the access each role requires, and how access is requested and approved. For a small merchant this is a one-to-two page matrix: cashier, manager, bookkeeper, and MSP technician roles mapped to POS functions, back-office systems, and network access. The MSP maintains the matrix, processes onboarding and offboarding tickets against it, and reviews it with the owner periodically. Assessors want to see that the documented model matches actual account assignments.',
          example: 'Compliant — Access matrix in IT Glue, updated 2026-05, defines four roles; spot check of eight user accounts against the matrix found no over-provisioning; access changes require a PSA ticket approved by the store manager.',
          type: 'administrative',
        },
        {
          code: '7.2',
          title: 'Access to System Components',
          description: 'Assign access to systems and data based on job classification and least privilege, and review it periodically.',
          explanation: 'Users, including administrators, must receive only the privileges their job requires, all access must be approved, and 4.0 adds a formal review of user accounts and privileges at least every six months. The MSP implements least privilege by removing local admin from daily-driver accounts, using separate admin accounts for technicians, and scoping POS permissions per role. Semiannual access reviews are run from the M365 admin center and POS user list, with results and any removals recorded in a ticket. Third-party and vendor accounts get the same scrutiny.',
          example: 'Partial — Least privilege enforced on workstations and M365, but the semiannual review completed 2026-06-18 found two former-employee POS accounts still active; disabled same day, and offboarding checklist updated to include the POS user list.',
          type: 'technical',
          auto: 'm365',
          autoCheck: 'least_privilege',
        },
        {
          code: '7.3',
          title: 'Access Control Systems',
          description: 'Enforce access rights through an access control system that denies all access by default.',
          explanation: 'Access decisions must be enforced by a technical system — not just policy — that covers all in-scope components and defaults to deny. In an MSP-managed small merchant environment this is Active Directory or Entra ID for Windows and cloud resources, the POS application role system for payment functions, and firewall policy for network paths. The MSP confirms the deny-by-default posture: no shared open shares, no generic all-access accounts, and NTFS or SharePoint permissions scoped by group. Configuration screenshots and group membership exports serve as evidence.',
          example: 'Compliant — Entra ID with security-group-based permissions on SharePoint and the file server; POS roles enforce function-level access; no Everyone-writable shares found in the 2026-06 permissions audit; firewall policies default-deny.',
          type: 'technical',
        },
      ],
    },
    {
      code: 'REQ-8',
      title: 'Identify Users and Authenticate Access',
      description: 'Ensure every user is uniquely identified and strongly authenticated, with MFA protecting all access into the cardholder data environment.',
      controls: [
        {
          code: '8.1',
          title: 'Identity Policies',
          description: 'Define and document processes for identifying users and authenticating access to system components.',
          explanation: 'Written procedures must cover the account lifecycle: how accounts are created, approved, modified, and disabled, plus authentication rules like password standards and MFA requirements. The MSP typically maintains this as an identity and authentication standard applied across managed clients, tailored with the merchant-specific systems it covers. The document should reflect 4.0 specifics such as 12-character minimum passwords and MFA into the CDE. Onboarding and offboarding checklists in the PSA make the procedures operational.',
          example: 'Compliant — Identity standard v2.1 on file covering account lifecycle, 14-character password minimum, and Duo MFA requirements; PSA onboarding/offboarding templates reference it; last review 2026-02.',
          type: 'administrative',
        },
        {
          code: '8.2',
          title: 'User Identification',
          description: 'Assign every user a unique ID and strictly manage the full lifecycle of user and administrator accounts.',
          explanation: 'Shared and generic accounts are prohibited for interactive use, every action must be traceable to an individual, terminated users must be revoked immediately, and inactive accounts removed within 90 days. This is a common failure point in small retail, where staff share a POS login or a common Windows account at the counter. The MSP creates individual accounts in M365, Windows, and the POS, monitors for inactive accounts, and executes same-day offboarding tickets. Vendor accounts are enabled only when needed and monitored while active.',
          example: 'Non-compliant — Front counter uses a shared Windows login (COUNTER1) for three cashiers; individual POS PINs exist but the OS session is shared. Remediation in progress: per-user fast-switching accounts scheduled for rollout by 2026-07-15, ticket #48377.',
          type: 'technical',
          auto: 'm365',
          autoCheck: 'unique_accounts',
        },
        {
          code: '8.3',
          title: 'Strong Authentication',
          description: 'Establish and manage strong authentication factors, including compliant passwords and secure credential handling.',
          explanation: 'PCI-DSS 4.0 raises the bar to 12-character minimum passwords (or 8 where systems cannot support 12), lockout after repeated failures, secure password resets with identity verification, and encryption of credentials in transit and storage. The MSP enforces password policy through Entra ID or AD group policy, configures lockout thresholds, and uses a helpdesk identity-verification step before resets. Where passwords are the only factor, they must be changed at least annually or usage analyzed dynamically, which is another reason MSPs deploy MFA broadly with Duo.',
          example: 'Compliant — Entra ID password policy enforces 14 characters with lockout at 10 attempts; helpdesk verifies identity via callback before resets; Duo MFA enrollment at 100 percent of 11 users as of 2026-06-30.',
          type: 'technical',
          severity: 'critical',
          auto: 'duo',
          autoCheck: 'mfa_enrolled',
        },
        {
          code: '8.4',
          title: 'MFA Implementation',
          description: 'Require multi-factor authentication for all access into the cardholder data environment and all remote access.',
          explanation: 'Under 4.0, MFA is required for all access into the CDE — not just administrators — as well as for all remote network access originating outside the network. The MSP implements Duo on the payment server logins, VPN, and remote access tools, and enforces MFA on M365. Technician access through the RMM must itself be MFA-protected, since MSP remote access is a direct path into the CDE. Enrollment reports from Duo provide continuous evidence of coverage.',
          example: 'Compliant — Duo enforced on payment server RDP, Fortigate SSL-VPN, and M365; MSP technicians authenticate to N-central with MFA; Duo report 2026-06-30 shows all in-scope users enrolled with no bypass codes outstanding.',
          type: 'technical',
          severity: 'critical',
          auto: 'duo',
          autoCheck: 'mfa_enrolled',
        },
        {
          code: '8.5',
          title: 'MFA Systems Configured',
          description: 'Configure multi-factor authentication systems so they resist replay, cannot be bypassed, and require success of all factors.',
          explanation: 'The MFA deployment itself must be sound: no user-initiated bypasses, factors independent of each other, replay-resistant methods, and access granted only after all factors succeed. In practice the MSP hardens the Duo or Entra configuration: disable SMS where possible in favor of push with number matching or FIDO2, remove standing bypass codes, restrict who can approve exception policies, and alert on MFA fatigue patterns. Exceptions must be time-boxed and documented rather than permanent policy holes.',
          example: 'Compliant — Duo push with number matching required; SMS disabled; bypass codes expire in 1 hour and require a PSA ticket; new-device enrollment requires helpdesk verification; configuration reviewed 2026-05.',
          type: 'technical',
        },
        {
          code: '8.6',
          title: 'Application/System Account Management',
          description: 'Strictly manage system and application accounts and their authentication factors, preventing interactive misuse.',
          explanation: 'Service accounts used by applications and systems must not be used for interactive logins except under documented, time-limited approval, and their passwords must not be hard-coded in scripts or config files in the clear. The MSP inventories service accounts (POS services, backup agent, scanning credentials), denies them interactive logon via group policy, stores their credentials in the password vault, and rotates them on a schedule and after suspected exposure. RMM and scanning credentials deserve special care since they are highly privileged.',
          example: 'Compliant — Four service accounts inventoried; interactive logon denied by GPO; credentials vaulted in Keeper with rotation every 180 days; Nodeware scan credential rotated 2026-06-01; no plaintext credentials found in scheduled task review.',
          type: 'administrative',
        },
      ],
    },
  ],
};
